"""Where else the manuscript restates a registered figure -- the surface §5.4's and §7's
guards each leave open, measured rather than assumed.

WHY THIS EXISTS
---------------
Two guards now watch registered figures in paper III, and between them they cover two
sections and one token class:

  * `test_cell_provenance` watches §5.4, and only its `\\d+\\.\\d+×` multipliers.
  * `test_ledger_provenance` watches §7's falsifier ledger, all figure kinds.

That looked like coverage until the second file's mutation drill measured it. The drill
mutated `**0.103 against 0.030**` expecting to break §7's row; `str.replace(..., 1)` took
the FIRST match, at line 1432 -- inside §5.4, ~150 lines above §7 -- and the suite stayed
green because §5.4's guard reads multipliers and 0.103 is not one. A false miss, and the
false miss was the finding:

    THE SAME REGISTERED FIGURE IS PRINTED IN UP TO FIVE PLACES IN THIS MANUSCRIPT.
    REG-003's α̂ appears eleven times across §4.4, §4.10, §5.4, §7 and §9. Two guards
    watched two of those. A re-run moves the result doc; whichever copies nobody
    updated stay behind, and every one of them is a well-formed sentence.

This file closes that by counting. For each figure §7's ledger declares, it pins HOW MANY
TIMES each section of the manuscript prints it. A restatement that appears, vanishes, or
drifts to a neighbouring value changes a count, and the suite says which section.

WHY COUNTS AND NOT A SET OF SECTIONS
------------------------------------
A section set would have been cheaper and is nearly useless: §4.10 prints α̂ = 0.408 five
times, so changing one of them to 0.409 leaves the set `{4.10, ...}` intact and the guard
green -- while 0.409, being declared nowhere, is watched by nothing at all. The count is
what makes a single drifted copy visible.

The cost is honest and worth naming: an edit that legitimately adds or removes a mention
turns this suite red and the author must update a number here. That is the same bargain
`CELLS` struck in `test_cell_provenance`, and the same one the phrase set and the
hand-audit ceilings struck elsewhere in this repo. The failure message names the section
and both counts so the update is mechanical.

WHAT IS DELIBERATELY NOT COUNTED
--------------------------------
Three of the ledger's figures are tokens the manuscript also uses for unrelated
quantities, where a count would pin the wrong thing and churn on edits that have nothing
to do with any registered run. They are named in `NOT_COUNTED` with the collision, and
`test_every_ledger_figure_is_either_counted_or_excused` makes the exclusion list a
declaration rather than an omission -- add a figure to §7's ledger and this file goes red
until someone puts it in one list or the other.

Offline, like every test here. It reads the manuscript only.
"""

from __future__ import annotations

import importlib.util
import pathlib
import re

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAPER = ROOT / "docs" / "papers" / "paper-III-dual-tensor" / "paper-III.md"


def _ledger():
    """The sibling guard's LEDGER, loaded by path so this does not depend on sys.path."""
    spec = importlib.util.spec_from_file_location(
        "_wt_ledger_provenance", pathlib.Path(__file__).with_name("test_ledger_provenance.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.LEDGER


LEDGER_FIGURES = {printed for _key, printed, *_rest in _ledger()}

# Tokens the manuscript uses for something else as well; counting them would pin the
# collision, not the restatement.
NOT_COUNTED = {
    "0.030": "δ = 0.030/yr is §4.4's top ladder rung, printed across §4.4, §4.7, §4.8 and "
             "§4.9; the token cannot tell it from REG-008's placebo rate.",
    "0.60":  "a swept decay rate in §4.2, §4.4 and §4.10 as well as REG-008's Fisher p.",
    "0.38":  "§4.7's fitted exponent shares the token with REG-007's Fisher p.",
}

# figure → {section label: times the section prints it}.  Generated by measurement, then
# read; the annotations say which occurrences are restatements of a registered run.
REACH = {
    # --- REG-002's ladder draws: §4.4 and §4.5 report them, §7 restates ----------------
    "0.32":   {"4.4": 1, "7": 1},
    # wealthTensor-52 · the Abstract counts below MOVED, and legitimately: the abstract was
    # 872 words / 5480 characters -- 2.85x arXiv's hard 1920-character metadata ceiling, so the
    # paper could not have been submitted with it -- and was cut to 247 words / 1564. Every
    # figure it lost is still in the body at the section this table already names, which is
    # what made the cut safe and what this file just proved. The guard fired on all three; it
    # is the only thing in the suite that noticed the abstract had changed at all.
    "0.41":   {"4.4": 2, "5.4": 1, "7": 1},
    "11.5":   {"1": 1, "4.4": 1, "4.5": 1, "7": 2, "Abstract": 1},
    "1.1":    {"4.4": 1, "7": 1},
    "23.8":   {"4.4": 1, "7": 1},
    "0.0079": {"4.4": 1, "7": 1},
    "1.30":   {"4.4": 1, "7": 1},
    "0.0123": {"4.4": 1, "7": 1},
    "1.58":   {"4.4": 1, "7": 1},
    "19.5":   {"4.4": 1, "7": 1},
    "66.2":   {"4.5": 1, "7": 1},
    "0.011":  {"4.5": 1, "7": 1},

    # --- REG-003: the widest reach in the paper, and the reason this file exists -------
    # α̂ = 0.408 is load-bearing in six sections at once. §4.9's copy is the youngest:
    # wealthTensor-104 repaired SHIP-LIST SL-1 there, where a relative clause had called
    # the rectangle's own fastest rate (0.333) "§5.4's measured rate". The repair names
    # §5.4's rate instead of mis-pointing at it, so the section prints α̂ once.
    "0.408":  {"4.10": 5, "4.4": 2, "4.9": 1, "5.4": 1, "7": 2, "9": 1},
    "0.383":  {"4.4": 1, "5.4": 1, "7": 1},
    "0.432":  {"4.4": 1, "5.4": 1, "7": 1},
    # wealthTensor-41 · T3 put REG-003's registered adverse cut into §4.4 twice — once as
    # the R column header, once in the domain sentence that compares it to the boundary
    # the CLAIM needs (0.3333) rather than to the calibration that flatters it (0.05).
    "0.327":  {"4.4": 2, "5.4": 1, "7": 1},
    "0.499":  {"5.4": 1, "7": 1},
    "1.210":  {"4.9": 1, "5.4": 1, "7": 1},
    "1.135":  {"4.10": 3, "4.9": 2, "5.4": 1, "7": 1},  # 4.10 was 1 until wealthTensor-101: wt185 III-5 replaced two bare
                                             # "§5.4's 0.150" attributions with the interval that width belongs to.
    "1.285":  {"4.10": 3, "4.9": 2, "5.4": 1, "7": 1},  # 4.10 was 1 until wealthTensor-101: wt185 III-5 replaced two bare
                                             # "§5.4's 0.150" attributions with the interval that width belongs to.
    # the off-diagonal headline: §5.4 reports it, §7 restates it, §9 leans on it
    "4.12":   {"5.4": 1, "7": 1, "9": 1},
    "2.02":   {"5.4": 1, "7": 1, "9": 1},
    "0.0002": {"5.4": 2, "7": 1},
    "695":    {"5.4": 2, "7": 2, "11": 1},   # +§11: T5's pull pin cites 688 → 695
    "688":    {"11": 2, "5.3": 3, "5.4": 1, "7": 1, "Abstract": 1},   # +§11, same pin

    # --- REG-006's re-crawl -----------------------------------------------------------
    "4.01":   {"5.4": 1, "7": 1},
    "2.01":   {"5.4": 1, "7": 1},
    "2.10":   {"5.4": 1, "7": 1},
    "700":    {"7": 1},
    "850":    {"7": 1},

    # --- REG-007 and REG-008: the pair §7 prints in one row ---------------------------
    # 0.103 at §5.4 is the occurrence the drill hit. It is now counted.
    "0.436":  {"5.4": 1, "7": 2},
    "0.403":  {"5.4": 1, "7": 2},
    "0.041":  {"7": 1},
    "0.032":  {"7": 1},
    "0.24":   {"7": 1},
    "0.103":  {"5.4": 1, "7": 1},
    "0.014":  {"5.4": 1, "7": 1},
    "0.068":  {"5.4": 1, "7": 1},
    # wealthTensor-80 · III-9: §5.4 asserted a zero over the WRONG denominator (644, the
    # mandated window, where REG-008 records one hit) instead of 281, the both-charges arm
    # where the zero actually lives. Repairing it puts 281 at the site of the claim, so the
    # figure now has the §5.4/§7 reach every other REG-007/008 number in this table has.
    "281":    {"5.4": 1, "7": 1, "9": 1},
    # 644 IS NOT COUNTED HERE, deliberately (wealthTensor-80). It is now restated in §5.4 and
    # §9 -- but this file inherits §7's curation by its own stated rule, and §7's ledger row
    # for REG-008 declares 281, not 644. Adding 644 without adding it to the ledger makes
    # this file assert its own selection rather than the paper's, which is the drift the
    # module exists to prevent. If §7 ever prints the window count, count it then.

    # --- REG-009 · the ladder inputs -------------------------------------------------
    # 0.974 is restated in §4.4 beside the calibration it corrects; the rest live in
    # §7 only, which is what a ledger row for a run nothing else cites looks like.
    "0.974":  {"4.4": 1, "7": 1},
    "0.659":  {"7": 1},
    "0.621":  {"7": 1},
    "0.696":  {"7": 1},
    "0.998":  {"7": 1},
    "0.139":  {"7": 1},
}


# --------------------------------------------------------------------------------------
# ONE LAYER OUT: restatements of runs §7's ledger does not declare
# --------------------------------------------------------------------------------------
# REACH above inherits §7's ledger, so it watches exactly the figures §7 chose to print.
# REG-004 and REG-005 are not in that ledger, and §4.10's comparison table restates ten
# of their numbers in a single grid that nothing in this suite reads. A re-run that moved
# α_ser at a three-year life from 0.4037 to 0.4031 would leave every test green.
#
# THE INCLUSION RULE, because a number-scrape of a RESULT doc does not give you one.
# Scraping RESULT-REG-004 for values that also appear in the manuscript returns 49
# figures, and the overwhelming majority are section cross-references (`4.2`, `5.4`),
# publication years (`1972`, `1982`), and fragments of hyphenated identifiers (`002`).
# Counting those would pin the paper's own table of contents. The filter that separates a
# reported statistic from a cross-reference is PRECISION: a figure carrying four or more
# significant digits is not a section label and not a year. It cuts 49 to 6 on REG-004
# and 62 to 10 on REG-005, and what survives is exactly §4.10's four-significant-figure
# passage plus REG-005's median k̂.
#
# This is the correction to the handoff that proposed this work: the mechanism does NOT
# "generalise unchanged". REACH could inherit §7's curation; this table has to state its
# own selection rule, and the rule is the deliverable.
RESULT_REACH = {
    # --- §4.10's grid: α_ser and α_eff at each rung of the disclosed rectangle ---------
    "0.4383": {"4.10": 1},    # α_ser  at a 40-year life
    "0.4368": {"4.10": 1},    # α_eff  at a 40-year life
    "0.4385": {"4.10": 1},    # α_ser  at 20 years
    "0.4388": {"4.10": 2},    # α_eff at 20 years AND α_ser at 10 -- the one repeat
    "0.4431": {"4.10": 1},    # α_eff  at 10 years
    "0.4370": {"4.10": 1},    # α_ser  at 5 years
    "0.4538": {"4.10": 1},    # α_eff  at 5 years
    "0.4037": {"4.10": 1},    # α_ser  at 3 years -- the cell that parts company
    "0.4758": {"4.10": 1},    # α_eff  at 3 years
    # --- REG-005's recovery of the lag shape ------------------------------------------
    "1.211":  {"4.10": 1},    # median k̂ over the recovery draws
}

# Same idea as NOT_COUNTED, for this table: a four-significant-figure token the
# manuscript also spends on something that is not a restatement.
RESULT_NOT_COUNTED = {
    "1.000": "a normalised entry in §3.1's worked example and a unit correlation in "
             "§5.3; four significant digits here are formatting, not precision.",
}


# --------------------------------------------------------------------------------------
# measurement
# --------------------------------------------------------------------------------------
def _section_labels(lines: list[str]) -> list[str]:
    """The section each line belongs to: the most recent heading, most specific wins.

    Numbered headings reduce to their number (`### 4.10 · The shape…` → `4.10`) so a
    retitled section does not churn every count; unnumbered ones keep their title
    (`Abstract`, `References`).
    """
    labels, current = [], "title"
    for line in lines:
        head = re.match(r"^#{1,4}\s+(.*)$", line)
        if head:
            title = head.group(1)
            numbered = re.match(r"^((?:Appendix )?[A-Z0-9]+(?:\.[0-9]+)*)\s*·", title)
            current = numbered.group(1) if numbered else title.split("·")[0].strip()
        labels.append(current)
    return labels


def _mentions(text: str, value: str) -> bool:
    """As in `test_ledger_provenance`: a number in its own right, not a fragment."""
    return re.search(rf"(?<![\d.]){re.escape(value)}(?![\d])", text) is not None


@pytest.fixture(scope="module")
def measured() -> dict[str, dict[str, int]]:
    lines = PAPER.read_text(encoding="utf-8").split("\n")
    labels = _section_labels(lines)
    out: dict[str, dict[str, int]] = {}
    for figure in list(REACH) + list(RESULT_REACH) + list(RESULT_NOT_COUNTED):
        counts: dict[str, int] = {}
        for label, line in zip(labels, lines):
            if _mentions(line, figure):
                counts[label] = counts.get(label, 0) + 1
        out[figure] = counts
    return out


# --------------------------------------------------------------------------------------
# the checks
# --------------------------------------------------------------------------------------
def test_every_ledger_figure_is_either_counted_or_excused():
    """§7's ledger and this file cannot drift apart silently.

    Add a figure to the ledger and it must be counted here or named in NOT_COUNTED with
    the collision that excuses it.
    """
    unaccounted = LEDGER_FIGURES - set(REACH) - set(NOT_COUNTED)
    assert not unaccounted, (
        f"§7's ledger declares figures this file neither counts nor excuses: "
        f"{sorted(unaccounted)}. Add each to REACH (with its measured per-section counts) "
        f"or to NOT_COUNTED (with the quantity whose token it collides with)."
    )
    stray = (set(REACH) | set(NOT_COUNTED)) - LEDGER_FIGURES
    assert not stray, (
        f"this file counts figures §7's ledger no longer declares: {sorted(stray)}. "
        f"If the ledger dropped them, drop them here too."
    )
    assert not (set(REACH) & set(NOT_COUNTED)), "a figure is both counted and excused"


@pytest.mark.parametrize("figure", sorted(REACH))
def test_the_manuscript_restates_the_figure_exactly_where_declared(figure, measured):
    """THE LOAD-BEARING CHECK.

    A copy that drifts, appears or vanishes changes a count. Section sets would not catch
    a single drifted copy among five; counts do.
    """
    declared, actual = REACH[figure], measured[figure]
    assert actual == declared, (
        f"{figure} is printed in a pattern the repository has not declared.\n"
        f"  declared: {dict(sorted(declared.items()))}\n"
        f"  measured: {dict(sorted(actual.items()))}\n"
        f"Sections whose count moved: "
        f"{sorted(set(declared) ^ set(actual) | {k for k in set(declared) & set(actual) if declared[k] != actual[k]})}. "
        f"Either a restatement drifted from the run that owns it -- the defect this file "
        f"exists for -- or the manuscript legitimately gained or lost a mention and the "
        f"count needs updating."
    )


# --------------------------------------------------------------------------------------
# the witnesses
# --------------------------------------------------------------------------------------
def test_this_file_actually_reaches_past_the_two_guarded_sections():
    """Otherwise it would be a third guard on the same two sections.

    §5.4 is watched for multipliers only and §7 is watched whole; every count below in a
    section that is neither -- §1, §4.x, §9, §11, the Abstract -- and every NON-multiplier
    count inside §5.4 is surface that nothing else in this suite reads.
    """
    guarded = {"7"}
    beyond = {f: {s: n for s, n in r.items() if s not in guarded}
              for f, r in REACH.items()}
    beyond = {f: r for f, r in beyond.items() if r}
    assert len(beyond) >= 30, (
        f"only {len(beyond)} figures reach outside §7; this file has stopped adding "
        f"coverage over test_ledger_provenance."
    )
    # the specific occurrence the mutation drill hit, named so it cannot quietly leave
    assert REACH["0.103"].get("5.4") == 1
    assert "×" not in "0.103", "0.103 is not a multiplier, so §5.4's guard never read it"


@pytest.mark.parametrize("figure", sorted(RESULT_REACH))
def test_the_manuscript_restates_the_unledgered_figure_exactly_where_declared(
        figure, measured):
    """The same load-bearing check, one layer out from §7's ledger.

    Most of these are printed exactly once, so the count is a presence guard: move the
    cell and its count goes to zero. That is the point -- a single silent cell in a
    comparison grid is precisely the copy nobody would notice.
    """
    declared, actual = RESULT_REACH[figure], measured[figure]
    assert actual == declared, (
        f"{figure} -- a REG-004/REG-005 restatement -- is printed in a pattern the "
        f"repository has not declared.\n"
        f"  declared: {dict(sorted(declared.items()))}\n"
        f"  measured: {dict(sorted(actual.items()))}\n"
        f"Either a re-run moved a cell of §4.10's comparison table and the manuscript "
        f"kept the old one, or the table legitimately changed and this count needs "
        f"updating with it."
    )


def test_the_unledgered_table_is_watched_by_nothing_else():
    """It must be ADDITIONAL surface, not a fourth guard on figures already covered."""
    overlap = (set(RESULT_REACH) | set(RESULT_NOT_COUNTED)) & (
        LEDGER_FIGURES | set(REACH) | set(NOT_COUNTED))
    assert not overlap, (
        f"{sorted(overlap)} are already watched by the ledger-derived tables; a figure "
        f"belongs to exactly one of them or the two will disagree on a legitimate edit."
    )
    assert not (set(RESULT_REACH) & set(RESULT_NOT_COUNTED))


def test_the_precision_rule_is_what_makes_this_table_possible():
    """The witness for the selection rule, so it cannot quietly become 'whatever we felt
    like pinning'.

    Every counted figure carries four or more significant digits. That is the property
    that separates a reported statistic from a section reference or a publication year,
    and without it the scrape returns 49 figures for REG-004 alone, most of them the
    paper's own cross-references.
    """
    def significant(fig: str) -> int:
        return len(fig.replace(".", "").lstrip("0")) if "." in fig else 0

    for fig in RESULT_REACH:
        assert significant(fig) >= 4, f"{fig} does not meet the stated precision rule"
    # and the rule genuinely excludes the noise it was written to exclude
    for noise in ("4.2", "5.4", "1982", "0.05"):
        assert significant(noise) < 4, f"{noise} would have passed the rule"


def test_a_drifted_copy_would_change_a_count(measured):
    """The counts are measurements, not decoration: perturb one and it disagrees."""
    figure = "0.408"
    assert measured[figure] == REACH[figure]
    tampered = dict(REACH[figure])
    tampered["4.10"] -= 1                      # one of the five copies drifts to 0.409
    assert measured[figure] != tampered, (
        "losing a copy of α̂ in §4.10 did not change the measurement, so the count is "
        "not reading what it claims to read."
    )
