#!/usr/bin/env bash
# docs/deliverable/build-public.sh
# =========================================================================================
# big-ceoDesk-braatzPapers · typeset the PUBLIC preprints, one PDF per paper, and nothing else.
#
# This is the artefact that gets posted to jason.braatz.ai. It differs from the review pair
# (build-v2-review.sh) in exactly three ways, and each one is a thing a public reader should
# not have to look at:
#
#   WT_COVER=off          no corpus cover page. The review build opens on "wealth-tensor: a
#                         point-in-time capture", lists four manuscripts and cites two internal
#                         build docs. A posted preprint is ONE paper and opens on its own title.
#   WT_FOOTER_STAMP=off   no 12-hex build commit on every sheet. That footer exists for P13a,
#                         which is a statement about the CAPTURE; a preprint reader is served
#                         by the author and the URL instead.
#   WT_PAPERS_ROOT        docs/papers-public -- the cut where the AI disclaimer is at the END,
#                         the contact is jason@braatz.ai, and the internal version string is
#                         gone. Generated by scripts/wt226_public_cut.py; never hand-edited.
#
# Everything else is deliberately identical to the review build: same fonts, same measure, same
# figure handling, same overfull-box-is-fatal discipline. The public PDF is not a lesser build.
#
# The canonical artefacts are checked afterwards rather than trusted, same as the review build:
# WT_CAPTURE and WT_TABLE_WIDTHS are pointed away from them, and then we CHECK that they moved.
#
#   ./build-public.sh          build both preprints
# =========================================================================================
set -uo pipefail
cd "$(dirname "$0")"
HERE="$(pwd)"
REPO="$(cd ../.. && pwd)"
DEST="${WT_PUBLIC_DEST:-$HERE/public}"
mkdir -p "$DEST"

echo "== regenerate the public cut"
python3 "$REPO/scripts/wt226_public_cut.py" || exit 1

build_one() {
  rel="$1"; out="$2"; label="$3"
  echo
  echo "== typeset $rel"
  WT_PAPERS_ROOT="docs/papers-public" \
  WT_PAPERS="$rel" \
  WT_OUT="$HERE/build-public-$out" \
  WT_CAPTURE="$DEST/$out.pdf" \
  WT_TABLE_WIDTHS="$HERE/TABLE-WIDTHS-v2.tsv" \
  WT_DOCLABEL="$label" \
  WT_COVER="off" \
  WT_FOOTER_STAMP="off" \
    ./build.sh --no-manifest || return 1
}

# Each paper gets its OWN WT_OUT: main.tex is regenerated per run and its contents list is
# built from the manuscript set, so sharing a build dir would leak one paper into the other.
FAIL=0
build_one "paper-II-redistribution/paper-II.md" \
          "braatz-2026-redistribution-parameter-space" \
          "Jason C Braatz · preprint · jason.braatz.ai" || FAIL=1
build_one "paper-III-dual-tensor/paper-III.md" \
          "braatz-2026-timeliness-durability-identification" \
          "Jason C Braatz · preprint · jason.braatz.ai" || FAIL=1
[ "$FAIL" -eq 0 ] || { echo; echo "REFUSED — a public build failed."; exit 1; }

# THE ONE THING THAT WOULD MAKE THIS SCRIPT A LIE.
echo
echo "== the canonical artefacts are untouched"
for f in wealth-tensor-capture.pdf LAYOUT-MANIFEST.json TABLE-WIDTHS.tsv TABLE-WIDTHS-v2.tsv; do
  if [ -n "$(git -C "$REPO" status --porcelain -- "docs/deliverable/$f")" ]; then
    echo "  FAIL   docs/deliverable/$f was modified by a public build"; FAIL=1
  else
    echo "  ok     docs/deliverable/$f"
  fi
done
[ "$FAIL" -eq 0 ] || { echo; echo "REFUSED — a public build wrote a canonical artefact."; exit 1; }

echo
echo "PUBLIC BUILD OK"
ls -la "$DEST"/*.pdf
