#!/usr/bin/env python3
"""wt129 — Paper II, sixth P7 pass (fourth INDEPENDENT read), wealthTensor-72.

Three findings, all from the QUANTIFIER SWEEP (WT-115) run for the first time on a
whole manuscript: enumerate every quantifier, read FORWARD from each to the end of
the document. 155 quantifier tokens across 108 lines were enumerated; three fell.

  II-19  §1 contribution 5 says every number below "is regenerated by a SINGLE
         COMMAND from a public repository". §7 needs TWO commands and says so in
         terms — and names the failure mode by name: "a single command named for
         numbers it does not produce is a provenance claim that reads as checked
         and is not." §1 makes the exact claim §7 forbids. Repair: name the two.

  II-20  §7's own opening says "every number is generated by simulation"; four
         lines later the same section carves out the three Var[log a] values as
         "quadrature rather than simulation output". wt128 propagated that carve-out
         into §5 limitation 5 and did NOT check §7's own universal — this is wt128's
         blast radius, found where the brief said to look. Repair APPENDS rather
         than rewrites, so the clause quoted verbatim in docs/END-TO-END-001.md and
         docs/RESULT-END-TO-END-001-E3.md survives as a literal substring (end-to-end
         is CLOSED; its quoted text is a dated record and is not rewritten).

  II-21  §2.3 says "no result below depends on a value of rho we picked". §3.1's
         flow rows are ALL at rho = 1 (its own footnote says so, "the implementation's
         default"), and §3.2's table shows the reachable flow Gini running 0.125 ->
         0.395 -> 0.994 across the rho axis. §3.1's headline frontier claim depends
         materially on the picked value. Repair states the value and keeps the
         defensible half (swept, not fitted).

NO NEW NUMBER IS INTRODUCED BY ANY OF THE THREE.

Guard kit (wt128's, plus two): generalised rewrap guard (normalised whole-document
equality under the intended replacements), a --census flag on the patch script itself
so census and anchors cannot drift apart, in-script criterion guards for P3e/P3g/P3n
fired BEFORE and AFTER, an explicit contiguity guard for the two mutation-control
strings, and a substring guard for the end-to-end quotation.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAPER = ROOT / "docs" / "papers" / "paper-II-redistribution" / "paper-II.md"
BAK = PAPER.with_suffix(".md.bak-wt72-p7")

# ---------------------------------------------------------------- replacements
REPL = [
    # II-19 · §1 contribution 5
    (
        "5. A **reproducible artefact**: every number below is regenerated by a single command from a\n"
        "   public repository, and the claims are held in place by the 18 tests in\n",
        "5. A **reproducible artefact**: every number below is regenerated from a public repository by\n"
        "   the two commands §7 names, and the claims are held in place by the 18 tests in\n",
    ),
    # II-21 · §2.3
    (
        "practice — and it is **swept rather than chosen**: no result below depends on a value of ρ we\n"
        "picked, and the paper's central result is a statement about the whole ρ axis.\n",
        "practice — and it is **swept rather than chosen**: §3.1's flow rows are stated at ρ = 1 and\n"
        "labelled as such, §3.2 sweeps the axis, and the paper's central result is a statement about the\n"
        "whole ρ axis rather than about a value of ρ chosen to make it come out right.\n",
    ),
    # II-20 · §7 opening
    (
        "used, because no empirical data is used at all — every number is generated by simulation.\n",
        "used, because no empirical data is used at all — every number is generated by simulation, save\n"
        "the three quadrature values the next bullet names.\n",
    ),
]

# Strings that must stay CONTIGUOUS ON ONE LINE — each is a live grep target.
CONTIGUOUS = [
    ("18 tests", "P3n greps the paper line-by-line for the derived count"),
    ("held in place by the 18 tests in", "scripts/redproof_paper_counts.py:36 mutation control"),
    ("test_a_flat_gini_does_not_mean_a_bounded_one", "P3j"),
    ("test_excess_demand_is_monotone_here_so_this_is_not_an_SMD_result", "P3j"),
]

# Substrings that must survive ANYWHERE (may wrap) — verbatim quotations held elsewhere.
SUBSTRING = [
    (
        "no empirical data is used at all — every number is generated by simulation",
        "quoted verbatim in docs/END-TO-END-001.md:282 and docs/RESULT-END-TO-END-001-E3.md:313",
    ),
    (
        "Endogenising ρ would make the flow base",
        "P3g positional criterion — it whitespace-JOINS §5 item 1 first, so this one wraps",
    ),
]


def norm(s):
    return re.sub(r"\s+", " ", s).strip()


# ------------------------------------------------------------ criterion guards
def p3e(text):
    """>=5 numbered items in the contributions list."""
    m = re.search(r"^\*\*Contributions.*?^## 2 ", text, re.S | re.M)
    body = m.group(0) if m else ""
    return len(re.findall(r"^[0-9]+\. ", body, re.M))


def p3g(text):
    """(bold-prefixed limitation count, item-1 phrase present)."""
    m = re.search(r"^## [0-9]+ · Limitations\n(.*?)^## ", text, re.S | re.M)
    body = m.group(1) if m else ""
    n = len(re.findall(r"^[0-9]+\. \*\*", body, re.M))
    item1 = re.search(r"^1\. (.*?)^2\. ", body, re.S | re.M)
    joined = norm(item1.group(1)) if item1 else ""
    return n, ("Endogenising ρ would make the flow base" in joined)


def criteria(text, label):
    e = p3e(text)
    g_n, g_phrase = p3g(text)
    print(f"  [{label}] P3e numbered contributions = {e} (need >=5)")
    print(f"  [{label}] P3g bold limitations       = {g_n} (need >=4)")
    print(f"  [{label}] P3g item-1 phrase in ITEM 1 = {g_phrase} (need True)")
    return e >= 5 and g_n >= 4 and g_phrase


# -------------------------------------------------------------------- census
def census():
    """Prove the anchors are unique in the tree BEFORE patching (WT-099)."""
    olds = [o for o, _ in REPL]
    scanned = hits = 0
    skip = {".git", ".venv", "__pycache__", "node_modules"}
    for p in ROOT.rglob("*"):
        if not p.is_file() or any(s in p.parts for s in skip):
            continue
        scanned += 1
        if p.suffix not in {".md", ".py", ".tsv", ".json", ".txt", ".log"}:
            continue
        try:
            t = p.read_text(encoding="utf-8")
        except Exception:
            continue
        for i, o in enumerate(olds, 1):
            if norm(o) in norm(t):
                hits += 1
                print(f"  anchor {i} → {p.relative_to(ROOT)}")
    print(f"census: {scanned} files scanned, {hits} anchor hit(s)")
    return hits


def main():
    text = PAPER.read_text(encoding="utf-8")

    if "--census" in sys.argv:
        h = census()
        # 3 anchors × 1 live paper + backups of the paper are allowed to match too;
        # what must hold is that no NON-backup file other than the paper matches.
        return 0 if h >= 3 else 1

    print("BEFORE:")
    if not criteria(text, "before"):
        sys.exit("criterion red BEFORE the patch — refusing to run")

    new = text
    for i, (old, rep) in enumerate(REPL, 1):
        if new.count(old) != 1:
            sys.exit(f"anchor {i} matched {new.count(old)} times, need exactly 1")
        new = new.replace(old, rep)

    # ---- generalised rewrap guard: the WHOLE normalised document must equal the
    # whole normalised document with the intended replacements applied. Proves the
    # three paragraphs say exactly what they should AND that nothing else moved.
    want = text
    for old, rep in REPL:
        want = want.replace(old, rep)
    assert norm(new) == norm(want), "rewrap guard: document text is not the intended text"
    print("  rewrap guard: normalised whole-document text == intended text ✓")

    # ---- contiguity guards. Each is asserted TRUE OF THE ORIGINAL first: a guard
    # that was never satisfied would otherwise report this patch as the regression.
    # (wealthTensor-72 wrote one such guard and it fired on the unedited file.)
    for s, why in CONTIGUOUS:
        if not any(s in line for line in text.split("\n")):
            sys.exit(f"guard is wrong, not the edit: {s!r} does not fit on one line BEFORE ({why})")
    for s, why in CONTIGUOUS:
        if not any(s in line for line in new.split("\n")):
            sys.exit(f"contiguity guard failed: {s!r} no longer fits on one line ({why})")
        if new.count(s) != text.count(s):
            sys.exit(f"contiguity guard: count of {s!r} changed ({why})")
    print(f"  contiguity guards: {len(CONTIGUOUS)}/{len(CONTIGUOUS)} ✓")

    # ---- substring guards (may wrap; checked on the normalised text), same before-check
    for s, why in SUBSTRING:
        if norm(s) not in norm(text):
            sys.exit(f"guard is wrong, not the edit: {s!r} absent BEFORE ({why})")
    for s, why in SUBSTRING:
        if norm(s) not in norm(new):
            sys.exit(f"substring guard failed: {s!r} ({why})")
    print(f"  substring guards: {len(SUBSTRING)}/{len(SUBSTRING)} ✓")

    # ---- the abstract must not move at all (244/1478, closest to ceiling in the batch)
    def abstract(t):
        a = t.index("## Abstract")
        k = t.index("**Keywords:**")
        return t[a:k]

    assert abstract(new) == abstract(text), "the abstract moved — it must not"
    print("  abstract byte-identical ✓")

    print("AFTER:")
    if not criteria(new, "after"):
        sys.exit("criterion red AFTER the patch — not writing")

    BAK.write_text(text, encoding="utf-8")
    PAPER.write_text(new, encoding="utf-8")
    print(f"\nwrote {PAPER.relative_to(ROOT)} (backup {BAK.name})")
    print(f"  {len(text)} → {len(new)} bytes, {len(REPL)} edits")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
