#!/usr/bin/env python3
"""wealthTensor-75 · Paper IV's independent P7 read -- six repairs, one dismissals row.

GUARD HONESTY (WT-118, wt129's rule; wt132 extended it to a test's assertions): every OLD
string is asserted present EXACTLY ONCE in the ORIGINAL before any substitution runs, and
the backups are written only after every guard has passed. A guard that was never satisfied
can never be reported as this patch's regression.

FINDINGS REPAIRED
  IV-1  §3 L179/L180 -- TWO cross-document section references written bare. `§3.1` resolves
        to nothing (Paper IV's §3 has no subsections) and `wt133` flags it. The line after it
        does the same thing with `§4`, which is WORSE: Paper IV HAS a §4 ("The tension,
        resolved explicitly"), so it resolves LOCALLY AND SILENTLY to the wrong section. Both
        belong to Paper III, whose §3.1 is the deferred-information table and whose §4.1 is
        "The class index". A sweep finds references that resolve to NOTHING; only a reader
        finds the ones that resolve to the WRONG THING.
  IV-2  §10 misroutes a replicator three ways, and §1 inherits the error.
        (a) it pairs `lambda_sensitivity.py` with `wt027_report.py`; wt027 imports only from
            `lag.py`. Paper III's own §11 names `wt002_lambda_report.py` for that module.
        (b) it names no command for the 4.12x / 2.02x diagonality rejection -- the borrowed
            result this paper leans on hardest, cited at L232, L328 and L597. Paper III §11
            names `wt026_severe_test.py`.
        (c) §1 says every number without a II/III citation "is from REG-013"; §10 says
            "everything else ... is regenerated by those papers' scripts". Both are false of
            ALL of §5's and §8's numbers -- which regenerate today, exactly, from THIS
            repository (`tests/test_excess_demand.py`, `scripts/wt071_refuter.py`).
  IV-3  §9.6's closing sentence -- "The three named here are the ones whose results the corpus
        actually uses" -- is contradicted by contribution 1, by the whole of §4, by §7's own
        "And on the aggregation literature specifically", and by an eight-entry Aggregation
        block in the references. WT-117's fourth instance: a claim about a set, contradicted
        by the document that makes it.
  IV-4  §6's floor states a universal the instrument could not see: "not one work in any of
        the three economics audiences also cites a CRISPR seed", measured against 4 000 of
        43 048 citing works -- 9.3 per cent. The paper gives the biophysical cap's magnitude
        (4 000 of 7 801) and withholds the floor cap's. The direction argument is sound and
        survives; the quantifier and the asymmetric disclosure do not. Also discloses that
        both true-audience sizes come from RESULT-REG-013 §2 and are NOT produced by the
        command §10 names -- verified against the committed run.json, which has no such field.
  IV-5  §10's non-circularity rationale describes a choice that was not available here:
        5efe626 IS the commit that adds this manuscript (+646 lines of paper-IV.md in the
        same commit). The sentence tells a reader the pin predates the paper. It does not.
  IV-6  §8 opens by declaring a test applied to "every entry" -- had this route worked, which
        sentence would be different? -- and the superposition entry does not answer it, while
        announcing it was rejected "before it reached a draft", which is §8's own definition
        of an advertisement rather than a disclosure. The entry now answers the test.

NOT DONE HERE, DELIBERATELY: `scripts/reg013_citation_whitespace.py` is NOT extended to record
each cluster's uncapped `meta.count`, though that is the fix that would make IV-4's two cap
fractions reproducible. §10 pins 5efe626 as "the last commit touching" that file, so editing it
falsifies the pin in the same stroke. The instrument change and the pin update must land
together, in a session that means to do both. Carded.
"""
from __future__ import annotations

import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
PAPER = ROOT / "docs/papers/paper-IV-composition/paper-IV.md"
DISMISSED = ROOT / "docs/crossref-dismissed.tsv"
TAG = "bak-wt134"

DISMISSED_ROW = (
    "paper-IV\t3.1\tA\tPaper III §3.1 -- the deferred-information table; named at the site "
    "(L179) after wt134, and Paper IV's own §3 has no subsections\n"
)

EDITS = [
    ("IV-1 §3 the two bare cross-document references",
     """and §3.1 reports what the distance between those two rates costs. The
household scale's quantitative answer is Paper III's, read before §4 indexes the holding by
asset class.""",
     """and Paper III §3.1 reports what the distance between those two rates costs. The
household scale's quantitative answer is Paper III's, read before that paper's §4 indexes the
holding by asset class."""),

    ("IV-2c §1 the provenance rule",
     """literature rather than on the model. Where a number appears below without a citation to II or III
it is from `REG-013` and is reproducible by the command in §10.""",
     """literature rather than on the model. Numbers appearing below without a citation to II or III come
from two places and §10 names the command for each: §6's are `REG-013`'s, and §5's and §8's are the
output of the fourth paper's apparatus, which is still in this repository and still runs."""),

    ("IV-4 §6 the floor's quantifier",
     """construction. It came back at **exactly zero**: not one work in any of the three economics
audiences also cites a CRISPR seed.""",
     """construction. It came back at **exactly zero**: of the 4 000 most-cited works citing a CRISPR
seed, not one is in any of the three economics audiences."""),

    ("IV-4 §6 the floor's cap, given its number",
     """biophysical overlaps. The floor's cap does the opposite and costs nothing, since a floor of exactly
zero is the strictest value available.""",
     """biophysical overlaps. The floor's cap is tighter still — 4 000 of 43 048, 9.3 per cent — and it
does the opposite and costs nothing: a cap can only remove intersections, so the measured floor is a
lower bound on the true one, and a floor of exactly zero is the strictest value available. Both
true-audience sizes are `RESULT-REG-013` §2's. The instrument stops retrieving at the cap and does
not print them, which makes them the two numbers in this section that §10's command does not
regenerate."""),

    ("IV-6 §8 the superposition entry answers §8's test",
     """physics metaphor — and the metaphor undersells a claim that is exactly stateable without it.""",
     """physics metaphor — and the metaphor undersells a claim that is exactly stateable without it. Had
it been sound, §5's account of what an agent's role *is* would read differently, which is what earns
it a place under this section's test despite its never having reached a draft."""),

    ("IV-3 §9.6 what the three named literatures are",
     """   this territory. The three named here are the ones whose results the corpus actually uses.""",
     """   this territory. The three named here are the three this paper *joins*. The aggregation
   literature is used, and heavily — §4 takes SMD as the boundary of the composition claim — but it
   is used as a limit rather than joined, which is why §7 treats it under a heading of its own."""),

    ("IV-2ab §10 the modules, their scripts, and §5/§8",
     """- **Papers cited as established results:** Paper II (`src/wealth_tensor/redistribution.py`,
  regenerated by `scripts/wt030_report.py`); Paper III (`src/wealth_tensor/lag.py` and
  `src/wealth_tensor/lambda_sensitivity.py`, regenerated by `scripts/wt027_report.py`)""",
     """- **Papers cited as established results:** Paper II (`src/wealth_tensor/redistribution.py`,
  regenerated by `scripts/wt030_report.py`); Paper III (`src/wealth_tensor/lag.py`, regenerated by
  `scripts/wt027_report.py`, and `src/wealth_tensor/lambda_sensitivity.py`, regenerated by
  `scripts/wt002_lambda_report.py`). The diagonality rejection cited in §3, §4.4 and §9 comes from
  neither: it is Paper III §5.4's, and its command is `python3 scripts/wt026_severe_test.py
  --universe pilot --onset peak`, with `--universe replication` for the second arm.
- **Regenerate §5 and §8:** `python3 -m pytest tests/test_excess_demand.py -q` for §5's schedule
  counts on the 399 interior grid points, its 500-point monotonicity sweep, and the twelve-point
  tie convention §8 records; `python3 scripts/wt071_refuter.py` for §5's crossing-height identity
  across all 25 allocations and for §8's *N*-dependence table and its control. This is the
  surviving apparatus of the fourth paper §8 describes. It is in this repository, and every number
  §5 and §8 report was re-run from it."""),

    ("IV-5 §10 the pin's rationale",
     """  every number in §6. The same non-circularity that governs Papers II and III applies: a paper
  cannot cite the commit that adds the paper, so what is pinned is the code, which is what a
  replicator needs and is verifiable today.""",
     """  every number in §6. It is also the commit that first added this manuscript: the instrument and
  the paper entered the repository together, so the pin is exact rather than approximate. What is
  pinned is the state of the code, which is what a replicator needs and is verifiable today."""),
]

# Every §N.M that legitimately belongs to another document. Mirrors docs/crossref-dismissed.tsv
# for paper-IV, plus 3.1, which this patch adds to that file.
FOREIGN = {"5.4", "A.1.2", "A.2.2", "3.1"}


def guard(text, needle, label):
    n = text.count(needle)
    if n != 1:
        sys.exit(f"GUARD FAILED (original, before any edit): {label} occurs {n} times in "
                 f"{PAPER.name}, expected exactly 1. Nothing was written.")


def section(text, head):
    """Body of a level-2 section. The final section has no following `## `, so the
    alternation must allow end-of-string -- without it the References guard is a guard
    that can never pass, which is the failure mode WT-118 exists to prevent."""
    m = re.search(re.escape(head) + r"\n(.*?)(?=\n## |\Z)", text, re.S)
    return m.group(1) if m else None


def main():
    paper = PAPER.read_text(encoding="utf-8")
    dismissed = DISMISSED.read_text(encoding="utf-8")

    # ---- every guard asserted against the ORIGINAL, before one byte moves --------------
    for label, old, _new in EDITS:
        guard(paper, old, label)
    if "paper-IV\t3.1\t" in dismissed:
        sys.exit("GUARD FAILED: paper-IV §3.1 already has a dismissals row. Nothing written.")

    abstract_before = section(paper, "## Abstract")
    assert abstract_before is not None, "abstract not found -- refusing to patch"
    refs_before = section(paper, "## References")
    assert refs_before is not None, "references not found -- refusing to patch"

    # ---- backups FIRST, then write -----------------------------------------------------
    for p in (PAPER, DISMISSED):
        shutil.copyfile(p, p.with_name(p.name + "." + TAG))

    for label, old, new in EDITS:
        paper = paper.replace(old, new, 1)
    if not dismissed.endswith("\n"):
        dismissed += "\n"
    dismissed += DISMISSED_ROW

    # ---- post-conditions ----------------------------------------------------------------
    assert section(paper, "## Abstract") == abstract_before, "the abstract moved -- refusing"
    assert section(paper, "## References") == refs_before, "the references moved -- refusing"
    for label, _old, new in EDITS:
        assert new in paper, f"a replacement did not land: {label}"

    # wt133 sweep 1, re-run on the PATCHED text (wt132's post-condition, kept)
    heads = set(re.findall(r"^#{1,6}\s+([A-Z]?\.?\d+(?:\.\d+)*)\s*·", paper, re.M))
    body = paper[:paper.index("\n## References")]
    used = set(re.findall(r"§\s*([A-Z]?\.?\d+(?:\.\d+)*)", body))
    unresolved = sorted(used - heads - FOREIGN)
    assert not unresolved, f"introduced unresolved cross-references: {unresolved}"

    # the bare §4 must be gone from the household paragraph, and §3.1 must be attributed
    assert "read before that paper's §4 indexes" in paper, "IV-1's §4 repair did not land"
    assert "and Paper III §3.1 reports" in paper, "IV-1's §3.1 repair did not land"
    assert "before §4 indexes the holding" not in paper, "the bare §4 survived"

    PAPER.write_text(paper, encoding="utf-8")
    DISMISSED.write_text(dismissed, encoding="utf-8")
    print(f"wt134: {len(EDITS)} manuscript edits, 1 dismissals row added.")
    print(f"       backups at *.{TAG}; abstract and references byte-identical;")
    print(f"       sweep 1 re-run on the patched text: 0 unresolved cross-references.")


if __name__ == "__main__":
    main()
