#!/usr/bin/env python3
"""wealthTensor-74 · Paper II's FIFTH independent P7 read -- four repairs, one instrument.

GUARD HONESTY (WT-118, wt129's rule, applied here without exception): every OLD string is
asserted present EXACTLY ONCE in the ORIGINAL before any substitution runs. A guard that was
never satisfied can never be reported as this patch's regression.

FINDINGS REPAIRED
  II-22  §7 twice scopes the manuscript's non-simulation numbers to "the three quadrature
         values" / "the three Var[log a] values". E[eta+] = 0.1073 is a FOURTH closed-form
         number, stated in §3.1 and printed by the very script §7 names
         (`wt077_tail_index.py`: "E[eta+] closed form = 0.107269").
  II-23  §3.3's "a lumpier assessment is very slightly stronger" is a general law with an
         INTERIOR MINIMUM. Measured: P = 1/2/4/10/20/30/50 -> 0.486/0.484/0.480/0.471/
         0.456/0.451/0.469 at T = 1200. The paper's own regeneration command prints the
         P = 50 row. The test that pinned the sentence swept p <= 20 and could not see it.
  II-24  §1's "The process responds to four numbers" is contradicted five lines later by
         contribution 1 ("plus the realisation share of the base ... a function of these
         alone") and by §3.2, where the same four numbers give Gini 0.125 or 0.994.
  II-26  §3.4's "which separates nothing" is false of its own numbers: 0.891 against 0.994
         is a 0.103 gap. The paragraph's real argument -- the ceiling, and N-dependence --
         is restored in its place.

INSTRUMENT (WT-092: what is the widest object this check's words claim, and the narrowest
thing it touches?) -- test_periodicity_is_second_order_at_a_matched_average_rate now sweeps
to P = 50 and pins the SHAPE it measured, not a monotonicity that stops where the test did.
Verified horizon-stable: the interior minimum and the turn hold at T = 600 and T = 1200.

BUG SPRAY: wt077's docstring names `RedistributionEconomy`; the class is
`RedistributiveEconomy`.
"""
from __future__ import annotations

import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
PAPER = ROOT / "docs/papers/paper-II-redistribution/paper-II.md"
TEST = ROOT / "tests/test_redistribution.py"
WT077 = ROOT / "scripts/wt077_tail_index.py"
TAG = "bak-wt132"

PAPER_EDITS = [
    ("II-24 §1", """not what the process responds to. The process responds to four numbers, and it cannot see where
they came from.""",
     """not what the process responds to. The process responds to five numbers — the levy's four
coordinates and the realisation share of its base (§3.2) — and it cannot see where any of them
came from."""),

    ("II-23 §3.3", """0.456 (*P* = 20). A
lumpier assessment is very slightly **stronger**, because it catches dispersion that has had time
to accumulate. An annual assessment is therefore not a watered-down continuous one — which is the
relevant observation for any levy assessed on a yearly cycle.""",
     """0.456 (*P* = 20). A
lumpier assessment is very slightly **stronger** over that range, because it catches dispersion
that has had time to accumulate. The effect is not monotone in *P*, and the sweep behind those two
endpoints says so: the minimum is **interior**, 0.451 at *P* = 30, and by *P* = 50 — where holding
the average rate at 0.02 requires the maximum rate, 1.00 — the Gini has returned to 0.469, above
its *P* = 20 value. The whole sweep spans 0.035, which is the operative fact: an annual assessment
is not a watered-down continuous one — which is the relevant observation for any levy assessed on
a yearly cycle."""),

    ("II-26 §3.4", """0.994, which separates nothing; their top""",
     """0.994 — a gap of 0.103 whose upper edge is the saturation ceiling itself, so any Gini threshold
would have to be drawn inside it and redrawn for every *N*; their top"""),

    ("II-22a §7", """used, because no empirical data is used at all — every number is generated by simulation, save
the three quadrature values the next bullet names.""",
     """used, because no empirical data is used at all — every measured number is generated by
simulation, save the four closed-form quantities the next bullet names."""),

    ("II-22b §7", """- **Regenerate every number in §3:** `python3 scripts/wt030_report.py` — except the three
  Var[log *a*] values in §3.1, which are quadrature over the multiplier's distribution rather than
  simulation output and come from `python3 scripts/wt077_tail_index.py`. The two commands are named""",
     """- **Regenerate every number in §3:** `python3 scripts/wt030_report.py` — except §3.1's four
  closed-form quantities: E[η⁺] = 0.1073 and the three Var[log *a*] values, which are quadrature
  over the multiplier's distribution rather than
  simulation output and come from `python3 scripts/wt077_tail_index.py`. The two commands are named"""),
]

TEST_OLD = '''def test_periodicity_is_second_order_at_a_matched_average_rate():
    """Levying rate*P every P periods is close to levying rate every period -- and slightly
    stronger, because a lumpy assessment catches dispersion that has had time to accumulate.

    Worth stating precisely: an annual 2.5% assessment is not a watered-down version of a
    continuous one. If anything the lumpiness helps, so periodicity cannot rescue or ruin a
    base -- it is a modifier on the effective rate, which is what makes base and rate the
    two structural coordinates and these two the trim.
    """
    gs = [stationary_gini(econ(base="stock", rate=0.02 * p, periodicity=p))
          for p in (1, 2, 4, 10, 20)]
    assert all(a >= b - 1e-9 for a, b in zip(gs, gs[1:]))   # monotone, lumpier is stronger
    assert max(gs) - min(gs) < 0.25                          # but only mildly so
'''

TEST_NEW = '''def test_periodicity_is_second_order_at_a_matched_average_rate():
    """Levying rate*P every P periods is close to levying rate every period. Lumpier is
    slightly stronger up to an INTERIOR MINIMUM near P = 30, and weaker after it -- so what
    this test pins is the SHAPE of the sweep and its small total spread, not monotonicity.

    wealthTensor-74. The previous version swept p in (1, 2, 4, 10, 20) and asserted
    monotonicity outright. The sweep the manuscript's own regeneration command prints
    (`scripts/wt030_report.py`) runs to P = 50, where the Gini returns ABOVE its P = 20
    value; the assertion could not see that because its subject stopped where its claim
    stopped. WT-092: what is the widest object this check's words claim, and what is the
    narrowest thing it actually touches? Verified horizon-stable at T = 600 and T = 1200.

    Worth stating precisely: an annual 2.5% assessment is not a watered-down version of a
    continuous one. Periodicity cannot rescue or ruin a base -- it is a modifier on the
    effective rate, which is what makes base and rate the two structural coordinates and
    these two the trim.
    """
    ps = (1, 2, 4, 10, 20, 30, 50)
    gs = [stationary_gini(econ(base="stock", rate=min(1.0, 0.02 * p), periodicity=p))
          for p in ps]
    assert all(a >= b - 1e-9 for a, b in zip(gs[:5], gs[1:5]))  # monotone THROUGH P = 20
    assert gs[ps.index(30)] < gs[ps.index(20)]                  # the minimum is interior
    assert gs[ps.index(50)] > gs[ps.index(20)]                  # and the effect turns back
    assert max(gs) - min(gs) < 0.25                             # the whole sweep is trim
'''

WT077_OLD = "RedistributionEconomy.run"
WT077_NEW = "RedistributiveEconomy.run"


def guard(text, needle, label, path):
    n = text.count(needle)
    if n != 1:
        sys.exit(f"GUARD FAILED (original, before any edit): {label} in {path.name} "
                 f"occurs {n} times, expected exactly 1. Nothing was written.")


def section(text, head):
    """Body of a level-2 section, for the abstract-identity guard."""
    m = re.search(re.escape(head) + r"\n(.*?)(?=\n## )", text, re.S)
    return m.group(1) if m else None


def main():
    paper = PAPER.read_text(encoding="utf-8")
    test = TEST.read_text(encoding="utf-8")
    wt077 = WT077.read_text(encoding="utf-8")

    # ---- every guard asserted against the ORIGINAL, before one byte moves -------------
    for label, old, _new in PAPER_EDITS:
        guard(paper, old, label, PAPER)
    guard(test, TEST_OLD, "periodicity test", TEST)
    guard(wt077, WT077_OLD, "wt077 class-name typo", WT077)

    abstract_before = section(paper, "## Abstract")
    assert abstract_before is not None, "abstract not found -- refusing to patch"

    # ---- backups FIRST, then write ----------------------------------------------------
    for p in (PAPER, TEST, WT077):
        shutil.copyfile(p, p.with_name(p.name + "." + TAG))

    for label, old, new in PAPER_EDITS:
        paper = paper.replace(old, new, 1)
    test = test.replace(TEST_OLD, TEST_NEW, 1)
    wt077 = wt077.replace(WT077_OLD, WT077_NEW, 1)

    # ---- post-conditions ---------------------------------------------------------------
    assert section(paper, "## Abstract") == abstract_before, "the abstract moved -- refusing"
    heads = set(re.findall(r"^#{1,6}\s+([A-Z]?\.?\d+(?:\.\d+)*)\s*·", paper, re.M))
    refs = set(re.findall(r"§\s*([A-Z]?\.?\d+(?:\.\d+)*)", paper))
    unresolved = sorted(refs - heads - {"4.1"})   # 4.1 is Benhabib et al.'s own, disclosed
    assert not unresolved, f"introduced unresolved cross-references: {unresolved}"
    for _label, _old, new in PAPER_EDITS:
        assert new in paper, "a replacement did not land"

    PAPER.write_text(paper, encoding="utf-8")
    TEST.write_text(test, encoding="utf-8")
    WT077.write_text(wt077, encoding="utf-8")
    print(f"wt132: {len(PAPER_EDITS)} manuscript edits, 1 test rewritten, 1 docstring typo.")
    print(f"       backups at *.{TAG}; abstract byte-identical; 0 unresolved cross-refs.")


if __name__ == "__main__":
    main()
