#!/usr/bin/env python3
"""wt144 · wealthTensor-81 · Paper IV's SECOND independent P7 read — the nine repairs.

Idempotent by construction: every edit asserts its OLD text is present exactly once
before replacing it, and re-running after a successful run raises SystemExit(0) with
ALREADY-APPLIED rather than corrupting the file.
"""
import pathlib, re, shutil, sys

REPO = pathlib.Path(__file__).resolve().parent.parent
P4 = REPO / "docs/papers/paper-IV-composition/paper-IV.md"
TEST = REPO / "tests/test_excess_demand.py"
TAG = "wt144"

EDITS = [
# ---- IV-1 · §10 names a command that does not produce the result -------------------
("""  neither: it is Paper III §5.4's, and its command is `python3 scripts/wt026_severe_test.py
  --universe pilot --onset peak`, with `--universe replication` for the second arm.""",
 """  neither: it is Paper III §5.4's, and its command is `python3
  scripts/wt089_recognition_and_offdiagonal.py`, which runs both universes in one pass and prints
  the 4.12× and 2.02× lifts, their *p* = 0.0002 and the power curve §3 quotes. `python3
  scripts/wt026_severe_test.py --universe pilot --onset peak` is Paper III §5.3's command, it
  answers a different question, and it prints none of those numbers; this bullet named it until
  wealthTensor-81."""),

# ---- IV-2 · §10's preamble contradicts §10's own bullets and §1 --------------------
("""This paper's own contribution is one measurement, on the citation graph rather than on a model.
Everything else it reports is cited from Paper II or Paper III and is regenerated by those papers'
scripts.""",
 """This paper's own contribution is one measurement, on the citation graph rather than on a model.
Numbers reported without a citation to Paper II or Paper III come from **two** places, which is
what §1 says: §6's are `REG-013`'s, and §5's and §8's are the surviving apparatus of the fourth
paper §8 describes. Everything else is cited from Paper II or Paper III and is regenerated by
those papers' scripts."""),

# ---- IV-3 · §10 names the test and the script for §5/§8 but never the module -------
("""  across all 25 allocations and for §8's *N*-dependence table and its control. This is the
  surviving apparatus of the fourth paper §8 describes. It is in this repository, and every number
  §5 and §8 report was re-run from it.""",
 """  across all 25 allocations and for §8's *N*-dependence table and its control. The module under
  both is `src/wealth_tensor/excess_demand.py` — this paper's only `src/` dependency that is not a
  sibling's, and the one this bullet named neither until wealthTensor-81. This is the surviving
  apparatus of the fourth paper §8 describes. It is in this repository, and every number §5 and §8
  report was re-run from it. §5's **399** interior grid points and §8's twelve-point **four** are
  *asserted* by `tests/test_excess_demand.py` rather than printed by it, so that command's output
  is a verdict and not a table."""),

# ---- IV-4 · "Two tests in the suite" is an exhaustive count and it is wrong --------
("""Two tests in the suite exist specifically to make overclaiming fail loudly —
`test_excess_demand_is_monotone_here_so_this_is_not_an_SMD_result`, which forbids §5's instance
being sold as an SMD result, and `test_a_flat_gini_does_not_mean_a_bounded_one`, which forbids a
saturating statistic being read as convergence. A test suite that constrains the author is a
different object from one that flatters him.""",
 """Two of the suite's overclaim-forbidding tests are named here, and the suite holds more than two:
`test_the_forbidden_claim_is_red` appears in two registration modules and Paper III names a third,
`test_pre001_constants_are_what_was_registered`.
`test_excess_demand_is_monotone_here_so_this_is_not_an_SMD_result` forbids §5's instance being sold
as an SMD result, which is this paper's own claim.
`test_a_flat_gini_does_not_mean_a_bounded_one` forbids a saturating statistic being read as
convergence, which is **Paper II's** claim and not this one's — this paper reports no Gini — and it
is named here because §3's sovereign scale rests on the result it guards. A test suite that
constrains the author is a different object from one that flatters him."""),

# ---- IV-5 · "It is not in this corpus" — the draft is in the repository ------------
("""arguing that supply and demand are not independent equations. It is not in this corpus. Had the""",
 """arguing that supply and demand are not independent equations. It is not published and is not one
of the papers this corpus joins; the draft itself is in the repository, superseded and marked so,
at `docs/papers/paper-I-price-formation/paper-I.md` — which is the only place the word count above
is checkable. Had the"""),

# ---- IV-6 · §7's fourth relocation names no work, no author and no constraint ------
("""Solow's scalar was not an error; it was the only object anyone could populate. The Austrian account
of the cycle names a different cause and describes the same architecture. SMD is not an opposing""",
 """Solow's scalar was not an error; it was the only object anyone could populate. SMD is not an opposing"""),

# ---- IV-7a · Robinson and Sraffa are used and credited nowhere ---------------------
("""the conclusions move. Capital as a malleable scalar is the second kind, and the Cambridge
controversy was fought over precisely that — Samuelson (1966) conceded that with reswitching
available the marginal-productivity account cannot be recovered from an aggregate capital measure.""",
 """the conclusions move. Capital as a malleable scalar is the second kind, and the Cambridge
controversy — opened by Robinson (1953), and given the reswitching apparatus by Sraffa (1960) —
was fought over precisely that: Samuelson (1966) conceded that with reswitching available the
marginal-productivity account cannot be recovered from an aggregate capital measure."""),

# ---- IV-7b · Mas-Colell, Whinston and Green sits in the list carrying no load ------
("""**And on the aggregation literature specifically.** SMD is treated in §4 at length and is not
re-argued here. The relation is complementarity: SMD is the theorem for the map, this framework is
the claim for the state, and neither implies the other.""",
 """**And on the aggregation literature specifically.** SMD is treated in §4 at length and is not
re-argued here; its textbook statement is Mas-Colell, Whinston and Green (1995). The relation is
complementarity: SMD is the theorem for the map, this framework is the claim for the state, and
neither implies the other."""),

# ---- IV-8 · §8's REG-001 entry does not pass §8's own stated test ------------------
("""four ways and the run produced no usable answer in either direction. It is recorded here as an
instrument dead end — which is what it is — and not as a result, because it never became one.""",
 """four ways and the run produced no usable answer in either direction. It is recorded here as an
instrument dead end — which is what it is — and not as a result, because it never became one.
Under this section's own test: had it returned, §5's identity would be reported as holding beyond
the single-good case, and §9's fifth limitation — that the zero-income-effect restriction is the
load-bearing one — would be a narrower claim than it now is."""),

# ---- IV-9 · the paper measures one absence and asserts the rest, and does not say so
("""8. **The whitespace measurement is about occupancy, not fertility.** `REG-013` can establish that
   an intersection is unoccupied. That it is worth occupying is what the argument has to earn, and
   the measurement cannot help with it.""",
 """8. **The whitespace measurement is about occupancy, not fertility.** `REG-013` can establish that
   an intersection is unoccupied. That it is worth occupying is what the argument has to earn, and
   the measurement cannot help with it.
9. **One of this paper's absences is measured and the rest are asserted, and §6's own standard is
   why that is worth stating.** §6 exists because *an absence found by searching is a property of
   the search*, and it measures the absence that motivates the paper. Three others are not
   measured: §1.1's *the input-output energy table has no lapse to report*, which is load-bearing
   for §4.3's *largely unmeasured rather than merely unassembled*; and §7's two
   within-literature absences, *has generally not had* an accounting-shaped object and *has mostly
   not had* a base. None of the three is known to be false. The point is that they stand on the
   evidentiary footing §6 was built to escape, and a reader is entitled to know which of this
   paper's absences were measured and which were looked for."""),
]

TEST_EDITS = [
("""    grid = np.linspace(M.min(), M.max(), 401)[1:-1]
    grid = np.array([p for p in grid if np.min(np.abs(M - p)) > 1e-9])
    assert grid.size > 300""",
 """    grid = np.linspace(M.min(), M.max(), 401)[1:-1]
    grid = np.array([p for p in grid if np.min(np.abs(M - p)) > 1e-9])
    # Paper IV §5 says "399 interior grid points" and §10 says this command regenerates it.
    # `> 300` let the manuscript's own number go unheld for the life of the paper; the tie
    # filter drops none of the 399, so the exact count is the assertion the sentence needs.
    assert grid.size == 399"""),
]

NEW_TEST = '''"""wealthTensor-81 · Paper IV §8's twelve-point tie convention, held by derivation.

WHY THIS EXISTS. Paper IV §10 says `python3 -m pytest tests/test_excess_demand.py -q`
regenerates "the twelve-point tie convention §8 records" — §8's claim that a 12-point grid
spanning the full range returns **four** distinct excess-demand schedules rather than one.
No test in this module measured it. `test_but_the_curves_themselves_are_not_invariant`
builds the same 12-point grid and counts DEMAND schedules (25), which is a different
number about a different object. So §10's promise was false for the life of the paper,
and the repair is to make the promise TRUE rather than to withdraw it.

The four is not an economic effect. Both grid endpoints coincide with data points; the
strict inequalities in `demand_at`/`supply_at` then disagree about a single agent whose
holding status varies by allocation; two endpoints x two holding states = four. §8 records
it as a near-miss — reporting it as a partial invariance would have published the central
claim one full step weaker than it is true.
"""
import numpy as np

from wealth_tensor.excess_demand import Market

RNG = np.random.default_rng(7)
M = RNG.lognormal(3.0, 0.6, 400)
S = 150


def _allocations(k=25):
    return [Market(M, S, rng=np.random.default_rng(i)) for i in range(k)]


def test_the_twelve_point_grid_returns_four_distinct_excess_demand_schedules():
    """§8's number, asserted where §10 promises a reader can regenerate it."""
    grid = np.linspace(M.min(), M.max(), 12)
    excess = {tuple(mk.excess_demand(float(p)) for p in grid) for mk in _allocations()}
    assert len(excess) == 4


def test_the_four_is_a_tie_convention_and_not_an_economic_effect():
    """The witness for §8's explanation: exclude the two endpoints and the four collapses to
    one. If this ever returns anything but 1, §8's account of WHY it was four is wrong and
    the sentence has to change, not the number."""
    grid = np.linspace(M.min(), M.max(), 12)[1:-1]
    excess = {tuple(mk.excess_demand(float(p)) for p in grid) for mk in _allocations()}
    assert len(excess) == 1


def test_the_twelve_point_grid_still_gives_twenty_five_demand_schedules():
    """Guards against the lazy repair of repointing the neighbouring test at excess demand:
    the 25 and the 4 are both real and are about different objects."""
    grid = np.linspace(M.min(), M.max(), 12)
    demand = {tuple(mk.demand_at(float(p)) for p in grid) for mk in _allocations()}
    assert len(demand) == 25
'''

NEW_GUARD = '''"""wealthTensor-81 · Paper IV may not claim an exhaustive suite-wide guard count.

WHY THIS EXISTS. Paper IV §10 said *"Two tests in the suite exist specifically to make
overclaiming fail loudly"* and named two. That is a count over the whole suite, and it was
wrong by a wide margin: `test_the_forbidden_claim_is_red` alone lives in two registration
modules, Paper III names `test_pre001_constants_are_what_was_registered` for the same
office, and there is a registered tripwire class besides.

This is the same shape `test_paper_test_counts_are_derived.py` was written for and the same
shape III-17 found in Paper III §11 — a count over a set the repository can enumerate,
written once in prose and never checked again. `tests/test_paper_test_counts_are_derived.py`
covers Papers II and III. Paper IV had no equivalent; this is it.

WHAT IT ASSERTS, AND WHAT IT DELIBERATELY DOES NOT. It does not assert HOW MANY
overclaim-forbidding tests the suite holds — that set has no mechanical definition and a
number pulled from a regex would be exactly the false precision this file exists to stop.
It asserts (a) that the manuscript does not make the exhaustive claim, (b) that both tests
it names still exist, which is what apparatus row P5j requires, and (c) that the two
sibling guards the repaired sentence cites are real, so the repair cannot rot into its own
phantom.
"""
import pathlib
import re

REPO = pathlib.Path(__file__).resolve().parent.parent
PAPER_IV = REPO / "docs/papers/paper-IV-composition/paper-IV.md"
TESTS = REPO / "tests"

NAMED_BY_PAPER_IV = (
    "test_excess_demand_is_monotone_here_so_this_is_not_an_SMD_result",
    "test_a_flat_gini_does_not_mean_a_bounded_one",
)
NAMED_AS_EVIDENCE_OF_MORE = (
    "test_the_forbidden_claim_is_red",
    "test_pre001_constants_are_what_was_registered",
)


def _flat(path):
    """The manuscript with newlines collapsed, so a markdown wrap cannot defeat a phrase grep."""
    return " ".join(path.read_text(encoding="utf-8").split())


def _defined(name):
    pattern = re.compile(r"^def %s\\b" % re.escape(name), re.MULTILINE)
    return [p.name for p in sorted(TESTS.glob("test_*.py"))
            if pattern.search(p.read_text(encoding="utf-8"))]


def test_paper_iv_does_not_claim_the_suite_holds_exactly_two_such_tests():
    """The defect itself. The old sentence, and the near-miss forms of it."""
    flat = _flat(PAPER_IV)
    for forbidden in (
        "Two tests in the suite exist specifically to make overclaiming fail loudly",
        "The two tests in the suite that exist",
        "the only two tests in the suite",
    ):
        assert forbidden not in flat, (
            "Paper IV §10 is again asserting an exhaustive count of the suite's "
            "overclaim-forbidding tests. There are more than two. Name the ones you mean "
            "and say the suite holds more; do not count a set nobody enumerated."
        )


def test_paper_iv_still_names_both_guards_apparatus_row_P5j_requires():
    flat = _flat(PAPER_IV)
    for name in NAMED_BY_PAPER_IV:
        assert name in flat, "P5j: Paper IV must name %s" % name


def test_every_guard_paper_iv_names_actually_exists():
    for name in NAMED_BY_PAPER_IV:
        assert _defined(name), "Paper IV names %s and no module defines it" % name


def test_the_sentence_s_evidence_that_there_are_more_than_two_is_real():
    """The repaired sentence cites two further guards as its warrant. If either disappears,
    the repair becomes an assertion about a set the reader cannot check -- which is the
    defect it replaced."""
    modules = _defined("test_the_forbidden_claim_is_red")
    assert len(modules) >= 2, (
        "Paper IV §10 says test_the_forbidden_claim_is_red appears in two registration "
        "modules; it now appears in %s" % modules
    )
    assert _defined("test_pre001_constants_are_what_was_registered"), (
        "Paper IV §10 credits Paper III with naming "
        "test_pre001_constants_are_what_was_registered; it no longer exists"
    )


def test_this_file_is_not_vacuous():
    """A negative-only guard passes on an empty file. This proves the reader works."""
    assert "overclaim" in _flat(PAPER_IV).lower()
    assert not _defined("test_a_name_no_module_defines_xyzzy")
'''


def apply(path, edits, label):
    text = path.read_text(encoding="utf-8")
    done = 0
    for old, new in edits:
        n = text.count(old)
        if n == 0:
            if text.count(new) == 1:
                print("  ALREADY  %s: %s..." % (label, old.split(chr(10))[0][:56]))
                continue
            raise SystemExit("ANCHOR NOT FOUND in %s:\n%r" % (path, old[:180]))
        if n != 1:
            raise SystemExit("ANCHOR AMBIGUOUS (%d) in %s:\n%r" % (n, path, old[:180]))
        text = text.replace(old, new, 1)
        done += 1
    if done:
        shutil.copy2(path, str(path) + ".bak-" + TAG)
        path.write_text(text, encoding="utf-8")
    print("  %s: %d edit(s) applied, %d already present" % (label, done, len(edits) - done))
    return done


def main():
    total = apply(P4, EDITS, "paper-IV.md")
    total += apply(TEST, TEST_EDITS, "tests/test_excess_demand.py")

    for rel, body in (("tests/test_paper_iv_tie_convention_is_counted.py", NEW_TEST),
                      ("tests/test_paper_iv_named_guards.py", NEW_GUARD)):
        p = REPO / rel
        if p.exists() and p.read_text(encoding="utf-8") == body:
            print("  ALREADY  %s" % rel)
        else:
            p.write_text(body, encoding="utf-8")
            print("  WROTE    %s" % rel)
            total += 1

    # ---- POST-CONDITIONS. Every one of these is a claim this script makes about the tree.
    p4 = P4.read_text(encoding="utf-8")
    flat = " ".join(p4.split())
    checks = [
        ("P1  wt026 is no longer named as the diagonality command",
         "wt089_recognition_and_offdiagonal.py" in p4),
        ("P2  wt026 is still named, correctly attributed to Paper III 5.3",
         "Paper III §5.3's command" in flat),
        ("P3  the exhaustive two-test count is gone",
         "Two tests in the suite exist specifically" not in flat),
        ("P4  P5j still satisfied - both guard names present",
         all(n in p4 for n in ("test_excess_demand_is_monotone_here_so_this_is_not_an_SMD_result",
                               "test_a_flat_gini_does_not_mean_a_bounded_one"))),
        ("P5  the excess_demand module is named",
         "src/wealth_tensor/excess_demand.py" in p4),
        ("P6  'It is not in this corpus.' is gone",
         "It is not in this corpus." not in flat),
        ("P7  paper-I's path is named where the word count is claimed",
         "docs/papers/paper-I-price-formation/paper-I.md" in p4),
        ("P8  the uncited Austrian relocation is gone",
         "The Austrian account" not in flat),
        ("P9  Robinson, Sraffa and Mas-Colell are now cited in the body",
         all(s in flat for s in ("Robinson (1953)", "Sraffa (1960)",
                                 "Mas-Colell, Whinston and Green (1995)"))),
        ("P10 §9 has a ninth limitation",
         "\n9. **One of this paper's absences is measured" in p4),
        ("P11 the REG-001 entry now answers §8's own test",
         "Under this section's own test" in flat),
        ("P12 NEGATIVE - no new commit SHA was introduced into the manuscript",
         sorted(set(re.findall(r"\b[0-9a-f]{7}\b", p4))) == sorted({"5efe626", "fff7063"})),
        ("P13 NEGATIVE - the §10 pin sentence is untouched",
         "the last commit touching" in flat),
        ("P14 the test's loose bound is gone",
         "assert grid.size > 300" not in TEST.read_text(encoding="utf-8")),
        ("P15 the test asserts the manuscript's own 399",
         "assert grid.size == 399" in TEST.read_text(encoding="utf-8")),
    ]
    bad = [n for n, ok in checks if not ok]
    for n, ok in checks:
        print("  %s  %s" % ("PASS" if ok else "FAIL", n))
    if bad:
        raise SystemExit("POST-CONDITIONS FAILED: %s" % bad)
    print("\nwt144: %d change(s), 15/15 post-conditions green." % total)


if __name__ == "__main__":
    main()
