#!/usr/bin/env python3
"""wt182 — the patch of record for wealthTensor-100, Paper IV's THIRD independent P7 read.

Four findings, four repairs, in charter §2's order (steelman / replace / cut / tee-up).
Pre-conditions assert the ORIGINAL text before any byte moves; post-conditions assert the
repaired text and, where the repair is a CUT, assert the cut string is gone.  Idempotent:
running it twice is a no-op that still passes every post-condition.

  IV-10  §10 named no command that prints §5's table.  scripts/wt018_report.py prints it,
         and the paper names that script nowhere.  STEELMAN: §10 names it.
  IV-11  §9 item 9 attributes a quoted phrase to §4.3; the phrase lives in §1.1.
         REPLACE: attribute it to §1.1's reading of §4.3.
  IV-12  §1 and §10 both say the paper's uncited numbers come from "two places"; §8's word
         count is a third.  CUT the census, keep the record-for-each.  And the count itself
         is 7,527 by the command §10 now names, not "roughly 7,400".
  IV-13  §8's stated test is unapplied to the "attacking the diagram" entry.  STEELMAN.
"""
import pathlib, re, shutil, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAPER = ROOT / "docs/papers/paper-IV-composition/paper-IV.md"
TESTS = ROOT / "tests/test_excess_demand.py"

EDITS = [
    # ---- IV-12a · §1: cut the census, name the third record -------------------------
    ("IV-12a", PAPER,
     "literature rather than on the model. Numbers appearing below without a citation to II or III come\n"
     "from two places and §10 names the record for each: §6's are `REG-013`'s, and its record is the\n"
     "committed output of that run rather than a command, because the instrument re-queries a live\n"
     "database; §5's and §8's are the output of the fourth paper's apparatus, which is still in this\n"
     "repository and still runs.\n",
     "literature rather than on the model. Numbers appearing below without a citation to II or III have\n"
     "their record named in §10, one for each: §6's are `REG-013`'s, and its record is the committed\n"
     "output of that run rather than a command, because the instrument re-queries a live database;\n"
     "§5's and §8's results are the output of the fourth paper's apparatus, which is still in this\n"
     "repository and still runs; and §8's word count for that paper is `wc -w` on its superseded draft.\n"),

    # ---- IV-12b · §8: the count the command returns ----------------------------------
    ("IV-12b", PAPER,
     "entry, and it cost the most. A complete draft existed — roughly 7,400 words, references verified —\n",
     "entry, and it cost the most. A complete draft existed — roughly 7,500 words, references verified —\n"),

    # ---- IV-13 · §8: the entry that never answered §8's own test ---------------------
    ("IV-13", PAPER,
     "diagram rather than the theory* — was fatal and unanswerable. **The cost was the most rhetorically\n"
     "satisfying claim the project had.**\n",
     "diagram rather than the theory* — was fatal and unanswerable. **The cost was the most rhetorically\n"
     "satisfying claim the project had.** Had the route worked, §5 would indict the Marshallian cross\n"
     "rather than explain what its two curves are for, and §4 would be defending a critique of general\n"
     "equilibrium instead of using SMD once, as a boundary.\n"),

    # ---- IV-11 · §9 item 9: the pointer that resolves to the wrong section -----------
    ("IV-11", PAPER,
     "   for §4.3's *largely unmeasured rather than merely unassembled*; and §7's two\n",
     "   for §1.1's reading of §4.3 as *largely unmeasured rather than merely unassembled*; and §7's\n"
     "   two\n"),

    # ---- IV-12c · §10: cut the census, name the third record ------------------------
    ("IV-12c", PAPER,
     "Numbers reported without a citation to Paper II or Paper III come from **two** places, which is\n"
     "what §1 says: §6's are `REG-013`'s, and §5's and §8's are the surviving apparatus of the fourth\n"
     "paper §8 describes. Everything else is cited from Paper II or Paper III and is regenerated by\n"
     "those papers' scripts.\n",
     "Numbers reported without a citation to Paper II or Paper III have their record named here, which\n"
     "is what §1 says: §6's are `REG-013`'s; §5's and §8's results are the surviving apparatus of the\n"
     # SL-6 (wealthTensor-104) re-pointed this clause at §10's new Regenerate bullet, which is
     # where the command AND its locale now live. IV-12c's claim -- that §10 names the THIRD
     # record rather than a census of two -- is unchanged; only the pointer moved. Re-keyed here
     # rather than left stale, so applying this patch from the census state writes today's text.
     "fourth paper §8 describes; and §8's word count for that paper is the `wc -w` named below, on the\n"
     "superseded draft §8 names. Everything else is cited from Paper II or Paper III and is regenerated by those papers'\n"
     "scripts.\n"),

    # ---- IV-10 · §10: the command that prints §5's table ----------------------------
    ("IV-10", PAPER,
     "- **Regenerate §5 and §8:** `python3 -m pytest tests/test_excess_demand.py -q` for §5's schedule\n"
     "  counts on the 399 interior grid points, its 500-point monotonicity sweep, and the twelve-point\n"
     "  tie convention §8 records; `python3 scripts/wt071_refuter.py` for §5's crossing-height identity\n"
     "  across all 25 allocations and for §8's *N*-dependence table and its control. The module under\n"
     "  both is `src/wealth_tensor/excess_demand.py` — this paper's only `src/` dependency that is not a\n"
     "  sibling's, and the one this bullet named neither until wealthTensor-81. This is the surviving\n"
     "  apparatus of the fourth paper §8 describes. It is in this repository, and every number §5 and §8\n"
     "  report was re-run from it. §5's **399** interior grid points and §8's twelve-point **four** are\n"
     "  *asserted* by `tests/test_excess_demand.py` rather than printed by it, so that command's output\n"
     "  is a verdict and not a table.\n",
     "- **Regenerate §5 and §8:** `python3 scripts/wt018_report.py` prints §5's table — the 399 interior\n"
     "  grid points, the 25 demand, 25 supply and one excess-demand schedules, and the 500-point\n"
     "  monotonicity sweep with **0** violations, endpoints **+249** and **−150**, and one sign change.\n"
     "  `python3 -m pytest tests/test_excess_demand.py -q` asserts those schedule counts and the\n"
     "  twelve-point tie convention §8 records; `python3 scripts/wt071_refuter.py` gives §5's\n"
     "  crossing-height identity across all 25 allocations and §8's *N*-dependence table and its\n"
     "  control. The module under all three is `src/wealth_tensor/excess_demand.py` — this paper's only\n"
     "  `src/` dependency that is not a sibling's, and the one this bullet named neither until\n"
     "  wealthTensor-81. This is the surviving apparatus of the fourth paper §8 describes. It is in this\n"
     "  repository, and every number §5 and §8 report was re-run from it. `tests/test_excess_demand.py`\n"
     "  *asserts* §5's **399** and §8's twelve-point **four** rather than printing them, so its output\n"
     "  is a verdict and not a table; `wt018_report.py` is the table.\n"),
]

NEW_TEST = '''

def test_the_monotone_sweep_endpoints_and_single_crossing_are_what_section_5_reports():
    """Paper IV §5's three unheld numbers, asserted here (wealthTensor-100, IV-10).

    §5 reports the 500-point sweep as "zero monotonicity violations ... running from +249 to
    -150 with one sign change".  `test_excess_demand_is_monotone_here_so_this_is_not_an_SMD_result`
    asserts only the monotonicity; the endpoints and the single crossing were printed by
    `scripts/wt018_report.py` -- which Paper IV named nowhere -- and asserted by nothing.
    Naming the script in §10 makes the numbers reproducible; this test makes them held.

    +249 is not a magic constant: at the grid minimum every agent but one values above the
    price, so z = (N - 1) - S = 399 - 150; at the maximum no agent does, so z = -S = -150.
    The NEGATIVE CONTROL below is what stops that from being a tautology dressed as a test.
    """
    mk = Market(M, S, rng=np.random.default_rng(3))
    zs = [mk.excess_demand(float(p)) for p in np.linspace(M.min(), M.max(), 500)]

    assert len(zs) == 500
    assert sum(1 for a, b in zip(zs, zs[1:]) if a < b) == 0          # zero violations
    assert (zs[0], zs[-1]) == (249, -150)                            # the endpoints §5 prints
    assert sum(1 for a, b in zip(zs, zs[1:]) if (a > 0) != (b > 0)) == 1   # one sign change

    # NEGATIVE CONTROL: a different stock moves the lower endpoint and only the lower endpoint,
    # so the pair above is a measurement of THIS market and not a constant this file invented.
    other = Market(M, 100, rng=np.random.default_rng(3))
    zs2 = [other.excess_demand(float(p)) for p in np.linspace(M.min(), M.max(), 500)]
    assert (zs2[0], zs2[-1]) == (299, -100)
    assert (zs2[0], zs2[-1]) != (zs[0], zs[-1])
'''


def _flat(s: str) -> str:
    """Whitespace-normalised. A LINE WRAP IS NOT A FACT ABOUT THE PAPER: matching a
    landed repair as an exact wrapped string makes any later reflow look like a missing
    repair, which is how this file went red at wealthTensor-104 with every one of its
    edits intact. Added there as a false-positive reduction (DoD 1.1's exception)."""
    return " ".join(s.split())


def apply_all():
    changed = []
    for tag, path, old, new in EDITS:
        txt = path.read_text()
        if _flat(new) in _flat(txt) and old not in txt:
            print(f"  {tag}: already applied (idempotent no-op)")
            continue
        if txt.count(old) != 1:
            sys.exit(f"PRECONDITION FAILED {tag}: expected exactly 1 occurrence, found {txt.count(old)}")
        bak = path.with_suffix(path.suffix + ".bak-wt182")
        if not bak.exists():
            shutil.copy2(path, bak)
        path.write_text(txt.replace(old, new, 1))
        changed.append(tag)
        print(f"  {tag}: applied")

    t = TESTS.read_text()
    if "test_the_monotone_sweep_endpoints_and_single_crossing_are_what_section_5_reports" not in t:
        bak = TESTS.with_suffix(TESTS.suffix + ".bak-wt182")
        if not bak.exists():
            shutil.copy2(TESTS, bak)
        TESTS.write_text(t.rstrip("\n") + "\n" + NEW_TEST)
        changed.append("IV-10-test")
        print("  IV-10-test: applied")
    else:
        print("  IV-10-test: already applied (idempotent no-op)")
    return changed


def postconditions():
    p = PAPER.read_text()
    t = TESTS.read_text()
    checks = [
        # --- IV-10
        ("P01 §10 names wt018_report.py", "`python3 scripts/wt018_report.py` prints §5's table" in p),
        ("P02 §10 carries the +249 endpoint", "endpoints **+249** and **−150**" in p),
        ("P03 §10 still calls the pytest output a verdict", "is a verdict and not a table" in p),
        ("P04 NEGATIVE: the old bullet opening is gone",
         "- **Regenerate §5 and §8:** `python3 -m pytest" not in p),
        ("P05 new test present", "def test_the_monotone_sweep_endpoints_and_single_crossing" in t),
        ("P06 new test carries a negative control", "NEGATIVE CONTROL" in t),
        ("P07 the named guard is untouched",
         "def test_excess_demand_is_monotone_here_so_this_is_not_an_SMD_result():" in t),
        # --- IV-11
        ("P08 §9.9 attributes the phrase to §1.1", "for §1.1's reading of §4.3 as" in p),
        ("P09 NEGATIVE: the misattribution is gone",
         "for §4.3's *largely unmeasured rather than merely unassembled*" not in p),
        ("P10 §1.1 still carries the phrase",
         "§4.3 finds the composed state\nlargely unmeasured rather than merely unassembled" in p),
        # --- IV-12
        ("P11 §10 names the third record",
         "`wc -w`" in _flat(p) and "superseded draft §8 names" in _flat(p)),
        ("P12 §1 names the third record", "`wc -w` on its superseded draft" in p),
        ("P13 NEGATIVE: §10's census is gone", "come from **two** places" not in p),
        ("P14 NEGATIVE: §1's census is gone", "from two places and §10 names the record" not in p),
        ("P15 the word count matches the command", "roughly 7,500 words" in p),
        ("P16 NEGATIVE: the old count is gone", "roughly 7,400 words" not in p),
        # --- IV-13
        ("P17 §8's entry answers §8's test", "Had the route worked, §5 would indict the Marshallian cross" in p),
        ("P18 §8's opening test is unchanged",
         "The test applied to every entry is: had this route worked, which sentence in this paper"
         in " ".join(p.replace("**", "").replace("*", "").split())),
        # --- invariants
        ("P19 §9 still has exactly nine limitations",
         len(re.findall(r"^\d+\. \*\*", p[p.index("## 9 · Limitations"):p.index("## 10 · Data")], re.M)) == 9),
        ("P20 no new hedge word introduced in §10",
         p[p.index("## 10 · Data"):].count("may be") == 0),
    ]
    bad = 0
    print(f"wt182 · post-conditions: {len(checks)} checks, 6 NEGATIVE")
    for name, ok in checks:
        print(f"  {'PASS' if ok else 'FAIL'}  {name}")
        bad += 0 if ok else 1
    return bad


if __name__ == "__main__":
    print("wt182 · applying")
    apply_all()
    n = postconditions()
    if n:
        sys.exit(f"wt182: {n} post-condition(s) FAILED")
    print("wt182: RC 0")
