# -*- coding: utf-8 -*-
EDITS = [
('IV-b02x', 'C-b', 'and why the claim that firm-level panels of\n*both* are public and free, which an earlier draft made here, is not made.', 'and why no claim that firm-level panels of\n*both* are public and free is made here.'),
('IV-b03', 'C-b', 'Note what is deliberately *not* argued here. The parallel claim about computation', 'A parallel claim about computation'),
('IV-b04', 'C-b', "This is also the paper's posture toward everything it disagrees with, and §7 states it as a\nmethod rather than leaving it as a habit: the disagreement", '§7 states this as a method: the disagreement'),
('IV-b05', 'C-b', ' A paper claiming clean composition across scales while citing SMD as a shield would be\n   contradicting itself, and §4 exists to make sure this one does not.', ' A paper claiming clean composition across scales while citing SMD as a shield would be\n   contradicting itself.'),
('IV-b06', 'C-b', ' is used\n   deliberately and named, rather than deployed four times by accident.', ' is used\n   deliberately and named.'),
('IV-b07', 'C-b', "and re-arguing them would be the\nduplication ADR-001's decomposition exists to avoid.", 'and the argument for each is in Paper III.'),
('IV-a01', 'C-a', 'which was tried, in this project, and did not survive (§8).', 'which §8 reports as tested and rejected.'),
('IV-a02', 'C-a', 'a form the next paragraph\nreports as tested and rejected, which changes what the link carries and not whether there is\none.', 'a form Paper III §5.4 rejects, which changes what the link carries and not whether there is\none.'),
('IV-b08', 'C-b', '**Three things follow, and the middle one is why this paper reports the rejection in the section\nthat makes the claim rather than only in its limitations.** First,', '**Three things follow.** First,'),
('IV-b09', 'C-b', "Third, and this is the\npart that runs against the paper's convenience, **Paper III's design", "Third, **Paper III's design"),
('IV-b10', 'C-b', "**An earlier draft of this section claimed more than three instances of one question, and the\ncorpus's first end-to-end test took the surplus away.** It said the three scales made *a chain\nrather than three analogies*. `END-TO-END-001` leg `E1` asked", '**A stronger reading — that the three scales make *a chain rather than three analogies* — was\nregistered, tested, and does not hold.** `END-TO-END-001` leg `E1` asked'),
('IV-b11', 'C-b', 'and the addition of §2.2 — which is\nwhat this section now claims and no more.', 'and the addition of §2.2 — and no more.'),
('IV-b12', 'C-b', '**before** the leg was run,\nprecisely so that it could not be renegotiated afterwards; `docs/RESULT-END-TO-END-001-E1.md`', '**before** the leg was run; `docs/RESULT-END-TO-END-001-E1.md`'),
('IV-b14', 'C-b', 'That is correct as far as it goes and it is the strongest thing anyone will say about this paper.', 'That is correct as far as it goes.'),
('IV-b15', 'C-b', '### 4.4 · The limits of the resolution, stated here rather than in §9', '### 4.4 · The limits of the resolution'),
('IV-b16', 'C-b', 'Three, and none of them is rhetorical.', 'Three.'),
('IV-b17', 'C-b', '§8\nrecords why, at length, because the route matters more than the destination here.*', '§8\nrecords why.*'),
('IV-b18', 'C-b', 'something quite different, and this is the part worth carrying into a paper about composition. At a clearing price', 'something quite different. At a clearing price'),
('IV-b19', 'C-b', '**The two results sit at opposite ends of\none axis, which is why they belong in the same paper**:', '**The two results sit at opposite ends of\none axis**:'),
('IV-b20', 'C-b', '**One qualification, and it is the first thing a referee will find, so it is here rather than in\n§9.**', '**One qualification.**'),
('IV-b21', 'C-b', 'Everything in this section is one move, applied deliberately, and naming it is more useful to a\nreader than performing it silently four times.', 'Everything in this section is one move, applied deliberately and named.'),
('IV-b22', 'C-b', 'Relocation is not politeness and it is not a rhetorical trick to be embarrassed about. For a claim\nthat spans three literatures it is a **structural** requirement:', 'For a claim\nthat spans three literatures, relocation is a **structural** requirement:'),
('IV-b23', 'C-b', '*This section is not a formality and it is not an appendix. The test applied to every entry is:', '*The test applied to every entry is:'),
('IV-b24', 'C-b', 'would be different? An abandonment that could\nnot have cost anything is an advertisement, not a disclosure.*', 'would be different?*'),
('IV-b25', 'C-b', '**"A chain rather than three analogies."** The sentence this paper\'s §3 carried until the corpus\'s\nfirst end-to-end test was run against it. Had it survived,', '**"A chain rather than three analogies."** Had it survived,'),
('IV-b26', 'C-b', 'This is Arrow–Debreu, Aumann and\n   Hildenbrand, and the same session had already established Hildenbrand (1994) as a source it\n   intended to cite.', 'This is Arrow–Debreu, Aumann and\n   Hildenbrand (1994).'),
('IV-b27', 'C-b', "largely unobserved.** This runs\n   directly against the paper's own comfort: §4.2's resolution", "largely unobserved.** §4.2's resolution"),
('IV-b28', 'C-b', "It is degraded rather than broken for a reason this paper's own\n   §4.2 supplies and should not be allowed to sound like a rescue: diagonality", 'It is degraded rather than broken for the reason §4.2 gives: diagonality'),
('IV-b29', 'C-b', "three others named here are asserted, and §6's\n   own standard is why that is worth stating.**", 'three others named here are asserted.**'),
('IV-b30', 'C-b', "evidentiary footing §6 was built to escape, and a reader is entitled to know which of this\n   paper's absences were measured and which were looked for.", 'evidentiary footing §6 was built to escape.'),
('IV-b31', 'C-b', "is named here because §3's sovereign scale rests on the result it guards. A test suite that\nconstrains the author is a different object from one that flatters him.", "is named here because §3's sovereign scale rests on the result it guards."),
('IV-b32', 'C-b', 'fourth paper died to its own referees. It is part of the record rather than an appendix to it.', 'fourth paper died to its own referees.'),
('IV-e01', 'C-e', ', and this bullet said "regenerate" until wealthTensor-82.', '.'),
('IV-e02', 'C-e', '; this bullet named it until\n  wealthTensor-81.', '.'),
('IV-e03', 'C-e', ', and the one this bullet named neither until\n  wealthTensor-81.', '.'),
('IV-x01', 'S1', '- **P2 · Decay.** The physical component degrades whether or not the degradation is recorded.', '- **P2 · Decay.** The physical component degrades absent maintenance. No store is inert.'),
('IV-x02', 'S1', 'and its mechanism κ is the sort of closed-form', 'and its compressive budget κ — which Paper II is\nexplicit is a budget and not a mechanism — is the sort of closed-form'),
('IV-x03', 'S1', 'statistically indistinguishable from no levy at all.', 'leaves the wealth vector exactly unchanged, agent by agent.'),
('IV-x04', 'S1', 'and Paper III §3.1 reports what the distance between those two rates costs. The', 'and Paper III §3.1 reports what deferring a change at those rates costs. The'),
]
