#!/usr/bin/env python3
"""wt206 — close the two patch-of-record guards Pass B's repairs reddened, by making
their subjects TIGHTER rather than their assertions weaker.

Both went red for the same structural reason, and it is this repo's sixth instance of it:
THE GUARD WAS WRONG ABOUT THE FILE, NOT THE FILE WRONG.

  `wt182` (paper-IV pass 3) · SL-6 re-pointed §10's word-count clause at the new
      Regenerate bullet and SL-9 rewrapped §9 item 9. Neither changed what wt182's IV-11
      and IV-12c repairs ASSERT -- both are still in the manuscript, in the same sections,
      saying the same thing. What broke is that wt182 matched them as EXACT LINE-WRAPPED
      STRINGS, so a later pass reflowing a paragraph makes an intact repair look absent.
      REPAIR: the idempotence branch matches `new` on whitespace-FLATTENED text, and P11
      does the same. A wrap is not a fact about the paper. `old` is STILL matched exactly
      on the raw text on both branches -- flattening that side too made IV-13 red, because
      several of these `old` strings are substrings of their own `new` once the newlines
      go, and a guard that cannot tell before from after is worse than one that churns.
      *This is a FALSE-POSITIVE reduction on an existing instrument -- DoD § 1.1's own
      named exception -- and not a new instrument.*

  `wt185` (paper-III pass 4) · its exactly-once family is the real guard, and it still
      passes. The check that broke was a GLOBAL count -- "§11 carries exactly five
      Regenerate bullets" -- which is a loose proxy for the double-apply it was written to
      forbid: it churns on any later pass that legitimately adds a bullet, which is exactly
      what SL-7 did (§11 now carries nine). REPAIR: assert the bullets are DISTINCT. That
      catches a double-applied bullet wherever it comes from -- broader on the real subject
      -- and is immune to honest growth. The post-condition COUNT is unchanged at 19.

Idempotent: NO-OP on a second run, exit 0.
"""
import sys, pathlib

R = pathlib.Path.home() / "repos/wealth-tensor"

W82 = R / "scripts/wt182_paperIV_p7pass3.py"
W85 = R / "scripts/wt185_paperIII_p7pass4.py"

E82 = [
 ("wt182 · IV-12c re-keyed to SL-6's refinement",
  '     "fourth paper §8 describes; and §8\'s word count for that paper is `wc -w` on the superseded draft\\n"\n'
  '     "§8 names. Everything else is cited from Paper II or Paper III and is regenerated by those papers\'\\n"',
  '     # SL-6 (wealthTensor-104) re-pointed this clause at §10\'s new Regenerate bullet, which is\n'
  '     # where the command AND its locale now live. IV-12c\'s claim -- that §10 names the THIRD\n'
  '     # record rather than a census of two -- is unchanged; only the pointer moved. Re-keyed here\n'
  '     # rather than left stale, so applying this patch from the census state writes today\'s text.\n'
  '     "fourth paper §8 describes; and §8\'s word count for that paper is the `wc -w` named below, on the\\n"\n'
  '     "superseded draft §8 names. Everything else is cited from Paper II or Paper III and is regenerated by those papers\'\\n"'),
 ("wt182 · flatten helper",
  "def apply_all():\n    changed = []\n",
  "def _flat(s: str) -> str:\n"
  '    """Whitespace-normalised. A LINE WRAP IS NOT A FACT ABOUT THE PAPER: matching a\n'
  "    landed repair as an exact wrapped string makes any later reflow look like a missing\n"
  "    repair, which is how this file went red at wealthTensor-104 with every one of its\n"
  "    edits intact. Added there as a false-positive reduction (DoD 1.1's exception).\"\"\"\n"
  '    return " ".join(s.split())\n\n\n'
  "def apply_all():\n    changed = []\n"),
 ("wt182 · idempotence on flattened text",
  "        if new in txt and old not in txt:\n",
  "        if _flat(new) in _flat(txt) and old not in txt:\n"),
 ("wt182 · P11 anchored on the concept",
  '        ("P11 §10 names the third record", "`wc -w` on the superseded draft\\n§8 names" in p),',
  '        ("P11 §10 names the third record",\n'
  '         "`wc -w`" in _flat(p) and "superseded draft §8 names" in _flat(p)),'),
]

E85 = [
 ("wt185 · distinct bullets, not a global count",
  '    a(("§11 carries exactly five Regenerate bullets (four before this pass), not six",\n'
  '       text.count("- **Regenerate ") == 5, True))',
  '    # A GLOBAL COUNT IS A LOOSE PROXY FOR DOUBLE-APPLICATION and churns on honest growth:\n'
  '    # wealthTensor-104 added four Regenerate bullets to §11 repairing SHIP-LIST SL-7, and\n'
  '    # this check went red on a manuscript that had gained provenance, not lost integrity.\n'
  '    # Distinctness is the tighter subject -- it forbids a duplicated bullet from ANY pass.\n'
  '    _bullets = [l for l in text.split("\\n") if l.startswith("- **Regenerate ")]\n'
  '    a(("§11\'s Regenerate bullets are all distinct — no bullet applied twice",\n'
  '       len(_bullets) == len(set(_bullets)), True))'),
]

def patch(path, edits):
    text = path.read_text(encoding="utf-8"); rc = 0
    for tag, old, new in edits:
        if new in text:
            print(f"  {tag}: NO-OP"); continue
        if old not in text:
            print(f"  {tag}: NOT FOUND"); rc = 2; continue
        if text.count(old) != 1:
            print(f"  {tag}: anchor not unique"); return 2
        text = text.replace(old, new); print(f"  {tag}: APPLIED")
    if rc: return rc
    if text != path.read_text(encoding="utf-8"):
        path.write_text(text, encoding="utf-8"); print("  wrote", path.name)
    return 0

def main():
    return patch(W82, E82) or patch(W85, E85)

sys.exit(main())
