#!/usr/bin/env python3
"""wt213 — the section 4.4 note: "known limitations of this review", one per manuscript.

DoD section 4.4 requires it and section 2.3 makes it the place S3 findings ship rather than
being swept under a rug.  CO-AUTHOR-CHARTER section 3.3 permits exactly ONE methods-disclosure
paragraph per manuscript and the charter WINS over the DoD, so the note is not a new
free-standing section: it is appended INSIDE each paper's existing sanctioned disclosure
section, which is the one home the charter already grants.  RULING, made rather than carded
(doctrine: any defensible position, pick and go).

It states facts and performs nothing.  Each note says what was checked mechanically, what by
hand, and what was not checked at all -- and names, per paper, the S3 findings that ship with
it.  Idempotent; exit 2 if a site matches neither state.
"""
import pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]

EDITS = [
("paper-II", "docs/papers/paper-II-redistribution/paper-II.md",
 "Pinning the last commit that touched the module rather than a bare placeholder is deliberate:",
 """**Known limitations of this review.** Every number above is regenerated by the two commands
named here, and a test suite pins the claims; the cross-references, the citation pointers and the
reference entries were checked by a sequence of independent reads rather than mechanically, and the
simulation figures rest on a single seed per configuration with seed-robustness asserted separately
rather than averaged in. Two things were not checked at all and are named rather than left to be
found: §1's characterisation of zakat is not supported here by a primary source, and §3.1's
*"4–7 %"* band is an under-claim — the sweep's largest residual is 6.831 %, so the band is true as
written and looser than the evidence requires.

Pinning the last commit that touched the module rather than a bare placeholder is deliberate:"""),

("paper-III", "docs/papers/paper-III-dual-tensor/paper-III.md",
 "The repository's `docs/` directory is public and holds the registrations, the run logs, the failed",
 """**Known limitations of this review.** The model results are checked mechanically — the closed
forms against simulation, the exchange against its mirror, the invariances against a numeraire
sweep, and all of it against a test suite that fails if a registered constant is edited. The
empirical results rest on one pull of a live endpoint, committed rather than re-fetched, and §11
says plainly that nothing here re-derives §5.3's figures from committed data. The reference list,
the cross-references and the section pointers were checked by repeated independent reads rather
than by any instrument, and the per-entry marks record how far each verification reached. What was
not checked at all: whether attrition differs systematically by tier, which §11's drop accounting
cannot answer and which is the one selection channel capable of manufacturing the reported null.

The repository's `docs/` directory is public and holds the registrations, the run logs, the failed"""),

("paper-IV", "docs/papers/paper-IV-composition/paper-IV.md",
 "The repository's `docs/` directory is deliberately public and is the project's working notebook,",
 """**Known limitations of this review.** This paper contributes one measurement of its own, and it
is pre-registered, run against a floor and a ceiling fixed in the same run, and replicated on the
live graph a day later; §6 states both truncations and what each costs. Everything else here is
cited from Papers II and III, so it inherits their checks and no more — a reader who rejects either
should reject the corresponding link. The joins between the three scales, the cross-paper
references and the relocation claims of §7 were checked by reading rather than by any instrument.
What was not checked at all: three of the four absences this paper asserts, which §9's ninth
limitation names one by one and declines to defend on the footing §6 was built to escape.

The repository's `docs/` directory is deliberately public and is the project's working notebook,"""),
]

def main():
    applied = already = 0; fail = []
    new = {}
    for tag, rel, anchor, repl in EDITS:
        p = ROOT / rel; t = p.read_text(encoding="utf-8")
        if t.count("**Known limitations of this review.**") == 1:
            already += 1; print("ALREADY-APPLIED %s" % tag); continue
        if t.count(anchor) == 1:
            new[rel] = t.replace(anchor, repl, 1); applied += 1; print("APPLIED         %s" % tag)
        else:
            fail.append(tag); print("!! NEITHER      %s  anchor count=%d" % (tag, t.count(anchor)))
    if fail:
        print("\nFAIL: %d site(s); NOTHING WRITTEN" % len(fail)); return 2
    for rel, t in new.items():
        p = ROOT / rel
        bak = p.with_suffix(".md.bak-wt213")
        if not bak.exists(): bak.write_text(p.read_text(encoding="utf-8"), encoding="utf-8")
        p.write_text(t, encoding="utf-8"); print("WROTE %s" % rel)
    print("\napplied=%d already=%d" % (applied, already)); return 0

if __name__ == "__main__":
    sys.exit(main())
